// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5393b9314a548245 "Osaka Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: '1' | '2' | '3' | '4' | '5' // Variant
 * background?: string // Background
 * selector?: string // Selector
 * image1?: {src: string, srcSet?: string, alt?: string} // Image 1
 * image2?: {src: string, srcSet?: string, alt?: string} // Image 2
 * image3?: {src: string, srcSet?: string, alt?: string} // Image 3
 * image4?: {src: string, srcSet?: string, alt?: string} // Image 4
 * image5?: {src: string, srcSet?: string, alt?: string} // Image 5
}} Props

 */
import { stdin_default, stdin_default2 } from "../chunks/chunk-4L3SU7PC.js";
import { routes } from "../chunks/chunk-RIZBGR4E.js";

// virtual:gallery/gallery-copy-2
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/od8SOlu4F1n5iiC2pBBT/V6Fu3rSlBFwYSScOaLUy/Pk68TThW3.js
import { jsx as _jsx3, jsxs as _jsxs3 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType3,
	cx as cx3,
	getFonts as getFonts2,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";

// /:https://framerusercontent.com/modules/xiWYosXGTOUiSw1xYssp/qM20Jh7W5MjCDzaNVWvE/FgrbiaL0J.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = [
	"LD918ZbGG",
	"zR0rvg3By",
	"b8dLAwujk",
	"pXFROP0zz",
	"aRY8eKw8E",
];
var serializationHash = "framer-nkcvI";
var variantClassNames = {
	aRY8eKw8E: "framer-v-1iidd5u",
	b8dLAwujk: "framer-v-18giejq",
	LD918ZbGG: "framer-v-cv5zlc",
	pXFROP0zz: "framer-v-1frdgxb",
	zR0rvg3By: "framer-v-oky5cp",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	duration: 0,
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	1: "LD918ZbGG",
	2: "zR0rvg3By",
	3: "b8dLAwujk",
	4: "pXFROP0zz",
	5: "aRY8eKw8E",
};
var getProps = ({
	height,
	id,
	image1,
	image2,
	image3,
	image4,
	image5,
	width,
	...props
}) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		CQuyllWoH: image2 !== null && image2 !== void 0 ? image2 : props.CQuyllWoH,
		CVqnpV02V: image5 !== null && image5 !== void 0 ? image5 : props.CVqnpV02V,
		E1VYOkQbB: image3 !== null && image3 !== void 0 ? image3 : props.E1VYOkQbB,
		fo7liKqhn: image4 !== null && image4 !== void 0 ? image4 : props.fo7liKqhn,
		ga3pCLb7N: image1 !== null && image1 !== void 0 ? image1 : props.ga3pCLb7N,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "LD918ZbGG",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		ga3pCLb7N,
		CQuyllWoH,
		E1VYOkQbB,
		fo7liKqhn,
		CVqnpV02V,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "LD918ZbGG",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-cv5zlc",
							className,
							classNames,
						)}
						data-framer-name={"1"}
						layoutDependency={layoutDependency}
						layoutId={"LD918ZbGG"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							...style,
						}}
						{...addPropertyOverrides(
							{
								aRY8eKw8E: {
									"data-framer-name": "5",
								},
								b8dLAwujk: {
									"data-framer-name": "3",
								},
								pXFROP0zz: {
									"data-framer-name": "4",
								},
								zR0rvg3By: {
									"data-framer-name": "2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								sizes:
									(componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.width) || "100vw",
								...toResponsiveImage(ga3pCLb7N),
							}}
							className={"framer-1folazx"}
							data-framer-name={"1"}
							layoutDependency={layoutDependency}
							layoutId={"v1Hw4y58e"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 1,
							}}
							variants={{
								aRY8eKw8E: {
									opacity: 0,
								},
								b8dLAwujk: {
									opacity: 0,
								},
								pXFROP0zz: {
									opacity: 0,
								},
								zR0rvg3By: {
									opacity: 0,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								sizes:
									(componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.width) || "100vw",
								...toResponsiveImage(CQuyllWoH),
							}}
							className={"framer-13jzxn3"}
							data-framer-name={"2"}
							layoutDependency={layoutDependency}
							layoutId={"lcDm09VcX"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0,
							}}
							variants={{
								zR0rvg3By: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								sizes:
									(componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.width) || "100vw",
								...toResponsiveImage(E1VYOkQbB),
							}}
							className={"framer-dbvfj3"}
							data-framer-name={"3"}
							layoutDependency={layoutDependency}
							layoutId={"mDAMDk81z"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0,
							}}
							variants={{
								b8dLAwujk: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								sizes:
									(componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.width) || "100vw",
								...toResponsiveImage(fo7liKqhn),
							}}
							className={"framer-bji27g"}
							data-framer-name={"4"}
							layoutDependency={layoutDependency}
							layoutId={"p9mhHOwQO"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0,
							}}
							variants={{
								pXFROP0zz: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								sizes:
									(componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.width) || "100vw",
								...toResponsiveImage(CVqnpV02V),
							}}
							className={"framer-1g0px11"}
							data-framer-name={"5"}
							layoutDependency={layoutDependency}
							layoutId={"M1ZCqLvR5"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0,
							}}
							variants={{
								aRY8eKw8E: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
							}}
							className={"framer-f75611"}
							data-framer-name={"6"}
							layoutDependency={layoutDependency}
							layoutId={"ugcSSk419"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0,
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
							}}
							className={"framer-103hafk"}
							data-framer-name={"7"}
							layoutDependency={layoutDependency}
							layoutId={"YjYNKLWkx"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0,
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
							}}
							className={"framer-9gijen"}
							data-framer-name={"8"}
							layoutDependency={layoutDependency}
							layoutId={"e1j1wMsow"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0,
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-nkcvI.framer-twvwpp, .framer-nkcvI .framer-twvwpp { display: block; }",
	".framer-nkcvI.framer-cv5zlc { height: 368px; overflow: hidden; position: relative; width: 656px; will-change: var(--framer-will-change-override, transform); }",
	".framer-nkcvI .framer-1folazx, .framer-nkcvI .framer-13jzxn3, .framer-nkcvI .framer-dbvfj3, .framer-nkcvI .framer-bji27g, .framer-nkcvI .framer-1g0px11, .framer-nkcvI .framer-f75611, .framer-nkcvI .framer-103hafk, .framer-nkcvI .framer-9gijen { bottom: 0px; flex: none; left: 0px; overflow: visible; pointer-events: none; position: absolute; right: 0px; top: 0px; }",
];
var FramerFgrbiaL0J = withCSS(Component, css, "framer-nkcvI");
var stdin_default3 = FramerFgrbiaL0J;
FramerFgrbiaL0J.displayName = "Gallery/Images Copy";
FramerFgrbiaL0J.defaultProps = {
	height: 368,
	width: 656,
};
addPropertyControls(FramerFgrbiaL0J, {
	variant: {
		options: ["LD918ZbGG", "zR0rvg3By", "b8dLAwujk", "pXFROP0zz", "aRY8eKw8E"],
		optionTitles: ["1", "2", "3", "4", "5"],
		title: "Variant",
		type: ControlType.Enum,
	},
	ga3pCLb7N: {
		title: "Image 1",
		type: ControlType.ResponsiveImage,
	},
	CQuyllWoH: {
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
	E1VYOkQbB: {
		title: "Image 3",
		type: ControlType.ResponsiveImage,
	},
	fo7liKqhn: {
		title: "Image 4",
		type: ControlType.ResponsiveImage,
	},
	CVqnpV02V: {
		title: "Image 5",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerFgrbiaL0J,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/OtCxPfY3yYUTA5OazRw1/YH0SfYH79TgoZNUfGvMA/lk7KWV6ZS.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	useActiveVariantCallback,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
var GalleryNavigationItemFonts = getFonts(stdin_default2);
var SVGFonts = getFonts(stdin_default);
var cycleOrder2 = [
	"uoqX6BTY6",
	"wW3K0zpUj",
	"laaWAmgqY",
	"Aa8cd0l5f",
	"j4VsBhjlb",
	"ZOdnxOrwK",
	"SggZwM72P",
	"BcDbgdQRB",
];
var serializationHash2 = "framer-aRc1a";
var variantClassNames2 = {
	Aa8cd0l5f: "framer-v-1viwgic",
	BcDbgdQRB: "framer-v-18o2z0b",
	j4VsBhjlb: "framer-v-oowfzz",
	laaWAmgqY: "framer-v-hxt018",
	SggZwM72P: "framer-v-1flappm",
	uoqX6BTY6: "framer-v-q7ab8m",
	wW3K0zpUj: "framer-v-9qwv9w",
	ZOdnxOrwK: "framer-v-1blr2mq",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition12 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 650,
	type: "spring",
};
var toResponsiveImage2 = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var isSet = (value) => {
	return value !== void 0 && value !== null && value !== "";
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2(React2.Fragment);
var humanReadableVariantMap2 = {
	1: "uoqX6BTY6",
	2: "wW3K0zpUj",
	3: "laaWAmgqY",
	4: "Aa8cd0l5f",
	5: "j4VsBhjlb",
	6: "ZOdnxOrwK",
	7: "SggZwM72P",
	8: "BcDbgdQRB",
};
var getProps2 = ({
	_1,
	_2,
	_3,
	_4,
	_5,
	_6,
	_7,
	_8,
	background,
	height,
	id,
	image1,
	image2,
	image3,
	image4,
	image5,
	image6,
	image7,
	image8,
	selector,
	width,
	...props
}) => {
	var _ref, _ref1, _ref2, _humanReadableVariantMap_props_variant, _ref3, _ref4;
	return {
		...props,
		cx33mnUE3:
			(_ref =
				image2 !== null && image2 !== void 0 ? image2 : props.cx33mnUE3) !==
				null && _ref !== void 0
				? _ref
				: {
						src: "https://framerusercontent.com/images/sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp?scale-down-to=512",
						srcSet:
							"https://framerusercontent.com/images/sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp?scale-down-to=512 512w,https://framerusercontent.com/images/sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp?scale-down-to=1024 1024w,https://framerusercontent.com/images/sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp 1456w",
					},
		FfrO1KV0Q: _3 !== null && _3 !== void 0 ? _3 : props.FfrO1KV0Q,
		FX_YoCLJm:
			(_ref1 =
				image1 !== null && image1 !== void 0 ? image1 : props.FX_YoCLJm) !==
				null && _ref1 !== void 0
				? _ref1
				: {
						src: "https://framerusercontent.com/images/lmFollwwBANyjurh7LnOrwRjzY.webp?scale-down-to=512",
						srcSet:
							"https://framerusercontent.com/images/lmFollwwBANyjurh7LnOrwRjzY.webp?scale-down-to=512 512w,https://framerusercontent.com/images/lmFollwwBANyjurh7LnOrwRjzY.webp?scale-down-to=1024 1024w,https://framerusercontent.com/images/lmFollwwBANyjurh7LnOrwRjzY.webp 1456w",
					},
		g8ToaZVmj: image3 !== null && image3 !== void 0 ? image3 : props.g8ToaZVmj,
		guL96G44I: _7 !== null && _7 !== void 0 ? _7 : props.guL96G44I,
		IqDVb43PR:
			(_ref2 =
				selector !== null && selector !== void 0
					? selector
					: props.IqDVb43PR) !== null && _ref2 !== void 0
				? _ref2
				: "var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255))",
		jR68EO0KP: _4 !== null && _4 !== void 0 ? _4 : props.jR68EO0KP,
		kV0neR1DF: image8 !== null && image8 !== void 0 ? image8 : props.kV0neR1DF,
		moyOFAv_J: _6 !== null && _6 !== void 0 ? _6 : props.moyOFAv_J,
		MvhWGEEJw: _8 !== null && _8 !== void 0 ? _8 : props.MvhWGEEJw,
		qO9woDsIE: image4 !== null && image4 !== void 0 ? image4 : props.qO9woDsIE,
		qX5aJY0_l: _1 !== null && _1 !== void 0 ? _1 : props.qX5aJY0_l,
		RthHlBIYj: _2 !== null && _2 !== void 0 ? _2 : props.RthHlBIYj,
		variant:
			(_ref3 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap2[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref3 !== void 0
				? _ref3
				: "uoqX6BTY6",
		XLzMbvsC3:
			(_ref4 =
				background !== null && background !== void 0
					? background
					: props.XLzMbvsC3) !== null && _ref4 !== void 0
				? _ref4
				: "var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
		y0fX7xmZq: image5 !== null && image5 !== void 0 ? image5 : props.y0fX7xmZq,
		YjoLglh7W: image7 !== null && image7 !== void 0 ? image7 : props.YjoLglh7W,
		YLJ1H6SSA: _5 !== null && _5 !== void 0 ? _5 : props.YLJ1H6SSA,
		ZrKNCUwGg: image6 !== null && image6 !== void 0 ? image6 : props.ZrKNCUwGg,
	};
};
var createLayoutDependency2 = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className,
		layoutId,
		variant,
		moyOFAv_J,
		guL96G44I,
		MvhWGEEJw,
		XLzMbvsC3,
		IqDVb43PR,
		FX_YoCLJm,
		cx33mnUE3,
		g8ToaZVmj,
		qO9woDsIE,
		y0fX7xmZq,
		ZrKNCUwGg,
		YjoLglh7W,
		kV0neR1DF,
		qX5aJY0_l,
		RthHlBIYj,
		FfrO1KV0Q,
		jR68EO0KP,
		YLJ1H6SSA,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "uoqX6BTY6",
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const Na8yZDTE3rdd9o6 = activeVariantCallback(async (...args) => {
		if (qX5aJY0_l) {
			const res = await qX5aJY0_l(...args);
			if (res === false) return false;
		}
		setVariant("uoqX6BTY6");
	});
	const Na8yZDTE311szjx7 = activeVariantCallback(async (...args) => {
		if (RthHlBIYj) {
			const res = await RthHlBIYj(...args);
			if (res === false) return false;
		}
		setVariant("wW3K0zpUj");
	});
	const Na8yZDTE31gni55d = activeVariantCallback(async (...args) => {
		if (FfrO1KV0Q) {
			const res = await FfrO1KV0Q(...args);
			if (res === false) return false;
		}
		setVariant("laaWAmgqY");
	});
	const Na8yZDTE317x9mbg = activeVariantCallback(async (...args) => {
		if (jR68EO0KP) {
			const res = await jR68EO0KP(...args);
			if (res === false) return false;
		}
		setVariant("Aa8cd0l5f");
	});
	const Na8yZDTE31gnkxv0 = activeVariantCallback(async (...args) => {
		if (YLJ1H6SSA) {
			const res = await YLJ1H6SSA(...args);
			if (res === false) return false;
		}
		setVariant("j4VsBhjlb");
	});
	const Na8yZDTE3n29jc7 = activeVariantCallback(async (...args) => {
		if (moyOFAv_J) {
			const res = await moyOFAv_J(...args);
			if (res === false) return false;
		}
		setVariant("ZOdnxOrwK");
	});
	const Na8yZDTE31ch7nh0 = activeVariantCallback(async (...args) => {
		if (guL96G44I) {
			const res = await guL96G44I(...args);
			if (res === false) return false;
		}
		setVariant("SggZwM72P");
	});
	const Na8yZDTE3oq0i8d = activeVariantCallback(async (...args) => {
		if (MvhWGEEJw) {
			const res = await MvhWGEEJw(...args);
			if (res === false) return false;
		}
		setVariant("BcDbgdQRB");
	});
	const ref1 = React2.useRef(null);
	const visible = isSet(g8ToaZVmj);
	const visible1 = isSet(qO9woDsIE);
	const visible2 = isSet(y0fX7xmZq);
	const visible3 = isSet(ZrKNCUwGg);
	const visible4 = isSet(YjoLglh7W);
	const visible5 = isSet(kV0neR1DF);
	const defaultLayoutId = React2.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport2();
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						className={cx2(
							serializationHash2,
							...sharedStyleClassNames,
							"framer-q7ab8m",
							className,
							classNames,
						)}
						data-framer-name={"1"}
						layoutDependency={layoutDependency}
						layoutId={"uoqX6BTY6"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backgroundColor: XLzMbvsC3,
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							...style,
						}}
						{...addPropertyOverrides2(
							{
								Aa8cd0l5f: {
									"data-framer-name": "4",
								},
								BcDbgdQRB: {
									"data-framer-name": "8",
								},
								j4VsBhjlb: {
									"data-framer-name": "5",
								},
								laaWAmgqY: {
									"data-framer-name": "3",
								},
								SggZwM72P: {
									"data-framer-name": "7",
								},
								wW3K0zpUj: {
									"data-framer-name": "2",
								},
								ZOdnxOrwK: {
									"data-framer-name": "6",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<motion2.div
								className={"framer-1n3o9kr-container"}
								layoutDependency={layoutDependency}
								layoutId={"a1NSNKKdJ-container"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									id: "a1NSNKKdJ",
									layoutId: "a1NSNKKdJ",
									Na8yZDTE3: Na8yZDTE3rdd9o6,
									qorJ6sE5a: IqDVb43PR,
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "kGqWZo08u",
									width: "100%",
									ztRBQIg9r: toResponsiveImage2(FX_YoCLJm),
									...addPropertyOverrides2(
										{
											Aa8cd0l5f: {
												variant: "JSBRhZ05q",
											},
											BcDbgdQRB: {
												variant: "JSBRhZ05q",
											},
											j4VsBhjlb: {
												variant: "JSBRhZ05q",
											},
											laaWAmgqY: {
												variant: "JSBRhZ05q",
											},
											SggZwM72P: {
												variant: "JSBRhZ05q",
											},
											wW3K0zpUj: {
												variant: "JSBRhZ05q",
											},
											ZOdnxOrwK: {
												variant: "JSBRhZ05q",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion2.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider>
							<motion2.div
								className={"framer-1e6cw9g-container"}
								layoutDependency={layoutDependency}
								layoutId={"sdh4iIfQM-container"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									id: "sdh4iIfQM",
									layoutId: "sdh4iIfQM",
									Na8yZDTE3: Na8yZDTE311szjx7,
									qorJ6sE5a: IqDVb43PR,
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "JSBRhZ05q",
									width: "100%",
									ztRBQIg9r: toResponsiveImage2(cx33mnUE3),
									...addPropertyOverrides2(
										{
											wW3K0zpUj: {
												variant: "kGqWZo08u",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion2.div>
						</ComponentViewportProvider>
						{visible && (
							<ComponentViewportProvider>
								<motion2.div
									className={"framer-14dlgvp-container"}
									layoutDependency={layoutDependency}
									layoutId={"cBDTKq1tN-container"}
								>
									{_jsx2(stdin_default2, {
										height: "100%",
										id: "cBDTKq1tN",
										layoutId: "cBDTKq1tN",
										Na8yZDTE3: Na8yZDTE31gni55d,
										qorJ6sE5a: IqDVb43PR,
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "JSBRhZ05q",
										width: "100%",
										ztRBQIg9r: toResponsiveImage2(g8ToaZVmj),
										...addPropertyOverrides2(
											{
												laaWAmgqY: {
													variant: "kGqWZo08u",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion2.div>
							</ComponentViewportProvider>
						)}
						{visible1 && (
							<ComponentViewportProvider>
								<motion2.div
									className={"framer-16vcahd-container"}
									layoutDependency={layoutDependency}
									layoutId={"EGf7el3Om-container"}
								>
									{_jsx2(stdin_default2, {
										height: "100%",
										id: "EGf7el3Om",
										layoutId: "EGf7el3Om",
										Na8yZDTE3: Na8yZDTE317x9mbg,
										qorJ6sE5a: IqDVb43PR,
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "JSBRhZ05q",
										width: "100%",
										ztRBQIg9r: toResponsiveImage2(qO9woDsIE),
										...addPropertyOverrides2(
											{
												Aa8cd0l5f: {
													variant: "kGqWZo08u",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion2.div>
							</ComponentViewportProvider>
						)}
						{visible2 && (
							<ComponentViewportProvider>
								<motion2.div
									className={"framer-1x2nzzn-container"}
									layoutDependency={layoutDependency}
									layoutId={"Xw5HsBhCL-container"}
								>
									{_jsx2(stdin_default2, {
										height: "100%",
										id: "Xw5HsBhCL",
										layoutId: "Xw5HsBhCL",
										Na8yZDTE3: Na8yZDTE31gnkxv0,
										qorJ6sE5a: IqDVb43PR,
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "JSBRhZ05q",
										width: "100%",
										ztRBQIg9r: toResponsiveImage2(y0fX7xmZq),
										...addPropertyOverrides2(
											{
												j4VsBhjlb: {
													variant: "kGqWZo08u",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion2.div>
							</ComponentViewportProvider>
						)}
						{visible3 && (
							<ComponentViewportProvider>
								<motion2.div
									className={"framer-g4qz63-container"}
									layoutDependency={layoutDependency}
									layoutId={"CD7fAO9h_-container"}
								>
									{_jsx2(stdin_default2, {
										height: "100%",
										id: "CD7fAO9h_",
										layoutId: "CD7fAO9h_",
										Na8yZDTE3: Na8yZDTE3n29jc7,
										qorJ6sE5a: IqDVb43PR,
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "JSBRhZ05q",
										width: "100%",
										ztRBQIg9r: toResponsiveImage2(ZrKNCUwGg),
										...addPropertyOverrides2(
											{
												ZOdnxOrwK: {
													variant: "kGqWZo08u",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion2.div>
							</ComponentViewportProvider>
						)}
						{visible4 && (
							<ComponentViewportProvider>
								<motion2.div
									className={"framer-riql11-container"}
									layoutDependency={layoutDependency}
									layoutId={"YTId9l7uO-container"}
								>
									{_jsx2(stdin_default2, {
										height: "100%",
										id: "YTId9l7uO",
										layoutId: "YTId9l7uO",
										Na8yZDTE3: Na8yZDTE31ch7nh0,
										qorJ6sE5a: IqDVb43PR,
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "JSBRhZ05q",
										width: "100%",
										ztRBQIg9r: toResponsiveImage2(YjoLglh7W),
										...addPropertyOverrides2(
											{
												SggZwM72P: {
													variant: "kGqWZo08u",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion2.div>
							</ComponentViewportProvider>
						)}
						{visible5 && (
							<ComponentViewportProvider>
								<motion2.div
									className={"framer-1fc2g3d-container"}
									layoutDependency={layoutDependency}
									layoutId={"yYTVvCsZ7-container"}
								>
									{_jsx2(stdin_default2, {
										height: "100%",
										id: "yYTVvCsZ7",
										layoutId: "yYTVvCsZ7",
										Na8yZDTE3: Na8yZDTE3oq0i8d,
										qorJ6sE5a: IqDVb43PR,
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "JSBRhZ05q",
										width: "100%",
										ztRBQIg9r: toResponsiveImage2(kV0neR1DF),
										...addPropertyOverrides2(
											{
												BcDbgdQRB: {
													variant: "kGqWZo08u",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion2.div>
							</ComponentViewportProvider>
						)}
						<motion2.div
							className={"framer-1lljr38"}
							data-framer-name={"Selector"}
							layoutDependency={layoutDependency}
							layoutId={"NtKa7fCeT"}
						>
							<motion2.div
								className={"framer-8s1rjt"}
								data-framer-name={"Helper"}
								layoutDependency={layoutDependency}
								layoutId={"xxUX9Pas3"}
							>
								<ComponentViewportProvider>
									<motion2.div
										className={"framer-l5aetz-container"}
										layoutDependency={layoutDependency}
										layoutId={"lNcFsArJT-container"}
									>
										{_jsx2(stdin_default, {
											customColor: IqDVb43PR,
											customPadding: 0,
											customStrokeWidth: 2,
											customSvgCode:
												'<svg width="86" height="50" viewBox="0 0 86 50" fill="none" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" clip-rule="evenodd" d="M9.96341 0H76.0366C81.5731 0 86 4.48832 86 9.94983V40.0502C86 45.5117 81.5731 50 76.0366 50H9.96342C4.42691 50 0 45.5117 0 40.0502V9.94983C0 4.48832 4.42691 0 9.96341 0ZM9.96341 1.92308C5.54024 1.92308 1.95455 5.51678 1.95455 9.94983V40.0502C1.95455 44.4832 5.54024 48.0769 9.96342 48.0769H76.0366C80.4598 48.0769 84.0455 44.4832 84.0455 40.0502V9.94983C84.0455 5.51678 80.4598 1.92308 76.0366 1.92308H9.96341Z" fill="black"/> </svg>',
											height: "100%",
											id: "lNcFsArJT",
											layoutId: "lNcFsArJT",
											lineCap: "butt",
											lineJoin: "miter",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
										})}
									</motion2.div>
								</ComponentViewportProvider>
							</motion2.div>
							<ComponentViewportProvider>
								<motion2.div
									className={"framer-lt1zad-container"}
									layoutDependency={layoutDependency}
									layoutId={"jhzPYA3Nu-container"}
									style={{
										opacity: 0,
									}}
								>
									{_jsx2(stdin_default2, {
										height: "100%",
										id: "jhzPYA3Nu",
										layoutId: "jhzPYA3Nu",
										qorJ6sE5a: "rgb(255, 255, 255)",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "JSBRhZ05q",
										width: "100%",
										ztRBQIg9r: toResponsiveImage2(cx33mnUE3),
									})}
								</motion2.div>
							</ComponentViewportProvider>
							<ComponentViewportProvider>
								<motion2.div
									className={"framer-sfkd1-container"}
									layoutDependency={layoutDependency}
									layoutId={"GJIlKv9_J-container"}
									style={{
										opacity: 0,
									}}
								>
									{_jsx2(stdin_default2, {
										height: "100%",
										id: "GJIlKv9_J",
										layoutId: "GJIlKv9_J",
										qorJ6sE5a: "rgb(255, 255, 255)",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "JSBRhZ05q",
										width: "100%",
										ztRBQIg9r: toResponsiveImage2(g8ToaZVmj),
									})}
								</motion2.div>
							</ComponentViewportProvider>
							{visible1 && (
								<ComponentViewportProvider>
									<motion2.div
										className={"framer-18l90t6-container"}
										layoutDependency={layoutDependency}
										layoutId={"S6XvitLXl-container"}
										style={{
											opacity: 0,
										}}
									>
										{_jsx2(stdin_default2, {
											height: "100%",
											id: "S6XvitLXl",
											layoutId: "S6XvitLXl",
											qorJ6sE5a: "rgb(255, 255, 255)",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "JSBRhZ05q",
											width: "100%",
											ztRBQIg9r: toResponsiveImage2(qO9woDsIE),
										})}
									</motion2.div>
								</ComponentViewportProvider>
							)}
							{visible2 && (
								<ComponentViewportProvider>
									<motion2.div
										className={"framer-177maw5-container"}
										layoutDependency={layoutDependency}
										layoutId={"qHaI8JCNU-container"}
										style={{
											opacity: 0,
										}}
									>
										{_jsx2(stdin_default2, {
											height: "100%",
											id: "qHaI8JCNU",
											layoutId: "qHaI8JCNU",
											qorJ6sE5a: "rgb(255, 255, 255)",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "JSBRhZ05q",
											width: "100%",
											ztRBQIg9r: toResponsiveImage2(y0fX7xmZq),
										})}
									</motion2.div>
								</ComponentViewportProvider>
							)}
							{visible3 && (
								<ComponentViewportProvider>
									<motion2.div
										className={"framer-18z70vu-container"}
										layoutDependency={layoutDependency}
										layoutId={"VtPADB_1i-container"}
										style={{
											opacity: 0,
										}}
									>
										{_jsx2(stdin_default2, {
											height: "100%",
											id: "VtPADB_1i",
											layoutId: "VtPADB_1i",
											qorJ6sE5a: "rgb(255, 255, 255)",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "JSBRhZ05q",
											width: "100%",
											ztRBQIg9r: toResponsiveImage2(ZrKNCUwGg),
										})}
									</motion2.div>
								</ComponentViewportProvider>
							)}
							{visible4 && (
								<ComponentViewportProvider>
									<motion2.div
										className={"framer-1w8atdn-container"}
										layoutDependency={layoutDependency}
										layoutId={"zLnTtHfnT-container"}
										style={{
											opacity: 0,
										}}
									>
										{_jsx2(stdin_default2, {
											height: "100%",
											id: "zLnTtHfnT",
											layoutId: "zLnTtHfnT",
											qorJ6sE5a: "rgb(255, 255, 255)",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "JSBRhZ05q",
											width: "100%",
											ztRBQIg9r: toResponsiveImage2(YjoLglh7W),
										})}
									</motion2.div>
								</ComponentViewportProvider>
							)}
							{visible5 && (
								<ComponentViewportProvider>
									<motion2.div
										className={"framer-8rglh6-container"}
										layoutDependency={layoutDependency}
										layoutId={"Voj25Yktv-container"}
										style={{
											opacity: 0,
										}}
									>
										{_jsx2(stdin_default2, {
											height: "100%",
											id: "Voj25Yktv",
											layoutId: "Voj25Yktv",
											qorJ6sE5a: "rgb(255, 255, 255)",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "JSBRhZ05q",
											width: "100%",
											ztRBQIg9r: toResponsiveImage2(kV0neR1DF),
										})}
									</motion2.div>
								</ComponentViewportProvider>
							)}
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-aRc1a.framer-1drhy4e, .framer-aRc1a .framer-1drhy4e { display: block; }",
	".framer-aRc1a.framer-q7ab8m { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; max-width: 380px; overflow: hidden; padding: 8px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-aRc1a .framer-1n3o9kr-container, .framer-aRc1a .framer-1e6cw9g-container, .framer-aRc1a .framer-14dlgvp-container, .framer-aRc1a .framer-16vcahd-container, .framer-aRc1a .framer-1x2nzzn-container, .framer-aRc1a .framer-g4qz63-container, .framer-aRc1a .framer-riql11-container, .framer-aRc1a .framer-1fc2g3d-container { flex: none; height: 46px; position: relative; width: 82px; }",
	".framer-aRc1a .framer-1lljr38 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: 52px; justify-content: flex-start; left: 0px; overflow: visible; padding: 8px; pointer-events: none; position: absolute; right: 0px; top: calc(50.00000000000002% - 52px / 2); z-index: 2; }",
	".framer-aRc1a .framer-8s1rjt { flex: none; height: 52px; overflow: visible; pointer-events: none; position: relative; width: 82px; }",
	".framer-aRc1a .framer-l5aetz-container { flex: none; height: 50px; left: calc(50.00000000000002% - 86px / 2); position: absolute; top: calc(50.00000000000002% - 50px / 2); width: 86px; z-index: 1; }",
	".framer-aRc1a .framer-lt1zad-container, .framer-aRc1a .framer-sfkd1-container, .framer-aRc1a .framer-18l90t6-container, .framer-aRc1a .framer-177maw5-container, .framer-aRc1a .framer-18z70vu-container, .framer-aRc1a .framer-1w8atdn-container, .framer-aRc1a .framer-8rglh6-container { flex: none; height: 46px; pointer-events: none; position: relative; width: 82px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-aRc1a.framer-q7ab8m, .framer-aRc1a .framer-1lljr38 { gap: 0px; } .framer-aRc1a.framer-q7ab8m > *, .framer-aRc1a .framer-1lljr38 > * { margin: 0px; margin-left: calc(4px / 2); margin-right: calc(4px / 2); } .framer-aRc1a.framer-q7ab8m > :first-child, .framer-aRc1a .framer-1lljr38 > :first-child { margin-left: 0px; } .framer-aRc1a.framer-q7ab8m > :last-child, .framer-aRc1a .framer-1lljr38 > :last-child { margin-right: 0px; } }",
	".framer-aRc1a.framer-v-9qwv9w .framer-8s1rjt, .framer-aRc1a.framer-v-hxt018 .framer-sfkd1-container, .framer-aRc1a.framer-v-1viwgic .framer-sfkd1-container, .framer-aRc1a.framer-v-oowfzz .framer-sfkd1-container, .framer-aRc1a.framer-v-1blr2mq .framer-sfkd1-container, .framer-aRc1a.framer-v-1flappm .framer-sfkd1-container, .framer-aRc1a.framer-v-18o2z0b .framer-sfkd1-container { order: 1; }",
	".framer-aRc1a.framer-v-9qwv9w .framer-lt1zad-container, .framer-aRc1a.framer-v-hxt018 .framer-lt1zad-container, .framer-aRc1a.framer-v-1viwgic .framer-lt1zad-container, .framer-aRc1a.framer-v-oowfzz .framer-lt1zad-container, .framer-aRc1a.framer-v-1blr2mq .framer-lt1zad-container, .framer-aRc1a.framer-v-1flappm .framer-lt1zad-container, .framer-aRc1a.framer-v-18o2z0b .framer-lt1zad-container { order: 0; }",
	".framer-aRc1a.framer-v-9qwv9w .framer-sfkd1-container, .framer-aRc1a.framer-v-hxt018 .framer-8s1rjt, .framer-aRc1a.framer-v-1viwgic .framer-18l90t6-container, .framer-aRc1a.framer-v-oowfzz .framer-18l90t6-container, .framer-aRc1a.framer-v-1blr2mq .framer-18l90t6-container, .framer-aRc1a.framer-v-1flappm .framer-18l90t6-container, .framer-aRc1a.framer-v-18o2z0b .framer-18l90t6-container { order: 2; }",
	".framer-aRc1a.framer-v-9qwv9w .framer-18l90t6-container, .framer-aRc1a.framer-v-hxt018 .framer-18l90t6-container, .framer-aRc1a.framer-v-1viwgic .framer-8s1rjt, .framer-aRc1a.framer-v-oowfzz .framer-177maw5-container, .framer-aRc1a.framer-v-1blr2mq .framer-177maw5-container, .framer-aRc1a.framer-v-1flappm .framer-177maw5-container, .framer-aRc1a.framer-v-18o2z0b .framer-177maw5-container { order: 3; }",
	".framer-aRc1a.framer-v-9qwv9w .framer-177maw5-container, .framer-aRc1a.framer-v-hxt018 .framer-177maw5-container, .framer-aRc1a.framer-v-1viwgic .framer-177maw5-container, .framer-aRc1a.framer-v-oowfzz .framer-8s1rjt, .framer-aRc1a.framer-v-1blr2mq .framer-18z70vu-container, .framer-aRc1a.framer-v-1flappm .framer-18z70vu-container, .framer-aRc1a.framer-v-18o2z0b .framer-18z70vu-container { order: 4; }",
	".framer-aRc1a.framer-v-9qwv9w .framer-18z70vu-container, .framer-aRc1a.framer-v-hxt018 .framer-18z70vu-container, .framer-aRc1a.framer-v-1viwgic .framer-18z70vu-container, .framer-aRc1a.framer-v-oowfzz .framer-18z70vu-container, .framer-aRc1a.framer-v-1blr2mq .framer-8s1rjt, .framer-aRc1a.framer-v-1flappm .framer-1w8atdn-container, .framer-aRc1a.framer-v-18o2z0b .framer-1w8atdn-container { order: 5; }",
	".framer-aRc1a.framer-v-9qwv9w .framer-1w8atdn-container, .framer-aRc1a.framer-v-hxt018 .framer-1w8atdn-container, .framer-aRc1a.framer-v-1viwgic .framer-1w8atdn-container, .framer-aRc1a.framer-v-oowfzz .framer-1w8atdn-container, .framer-aRc1a.framer-v-1blr2mq .framer-1w8atdn-container, .framer-aRc1a.framer-v-1flappm .framer-8s1rjt, .framer-aRc1a.framer-v-18o2z0b .framer-8rglh6-container { order: 6; }",
	".framer-aRc1a.framer-v-9qwv9w .framer-8rglh6-container, .framer-aRc1a.framer-v-hxt018 .framer-8rglh6-container, .framer-aRc1a.framer-v-1viwgic .framer-8rglh6-container, .framer-aRc1a.framer-v-oowfzz .framer-8rglh6-container, .framer-aRc1a.framer-v-1blr2mq .framer-8rglh6-container, .framer-aRc1a.framer-v-1flappm .framer-8rglh6-container, .framer-aRc1a.framer-v-18o2z0b .framer-8s1rjt { order: 7; }",
	".framer-aRc1a.framer-v-oowfzz.framer-q7ab8m, .framer-aRc1a.framer-v-oowfzz .framer-1lljr38, .framer-aRc1a.framer-v-1blr2mq.framer-q7ab8m, .framer-aRc1a.framer-v-1blr2mq .framer-1lljr38, .framer-aRc1a.framer-v-1flappm.framer-q7ab8m, .framer-aRc1a.framer-v-1flappm .framer-1lljr38, .framer-aRc1a.framer-v-18o2z0b.framer-q7ab8m, .framer-aRc1a.framer-v-18o2z0b .framer-1lljr38 { justify-content: flex-end; }",
];
var Framerlk7KWV6ZS = withCSS2(Component2, css2, "framer-aRc1a");
var stdin_default4 = Framerlk7KWV6ZS;
Framerlk7KWV6ZS.displayName = "Gallery/Navigation Copy";
Framerlk7KWV6ZS.defaultProps = {
	height: 62,
	width: 184,
};
addPropertyControls2(Framerlk7KWV6ZS, {
	variant: {
		options: [
			"uoqX6BTY6",
			"wW3K0zpUj",
			"laaWAmgqY",
			"Aa8cd0l5f",
			"j4VsBhjlb",
			"ZOdnxOrwK",
			"SggZwM72P",
			"BcDbgdQRB",
		],
		optionTitles: ["1", "2", "3", "4", "5", "6", "7", "8"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	moyOFAv_J: {
		title: "6",
		type: ControlType2.EventHandler,
	},
	guL96G44I: {
		title: "7",
		type: ControlType2.EventHandler,
	},
	MvhWGEEJw: {
		title: "8",
		type: ControlType2.EventHandler,
	},
	XLzMbvsC3: {
		defaultValue:
			'var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5)) /* {"name":"1"} */',
		title: "Background",
		type: ControlType2.Color,
	},
	IqDVb43PR: {
		defaultValue:
			'var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255)) /* {"name":"12"} */',
		title: "Selector",
		type: ControlType2.Color,
	},
	FX_YoCLJm: {
		__defaultAssetReference:
			"data:framer/asset-reference,lmFollwwBANyjurh7LnOrwRjzY.webp?originalFilename=blue-1.webp&preferredSize=auto",
		title: "Image 1",
		type: ControlType2.ResponsiveImage,
	},
	cx33mnUE3: {
		__defaultAssetReference:
			"data:framer/asset-reference,sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp?originalFilename=orange-1.webp&preferredSize=auto",
		title: "Image 2",
		type: ControlType2.ResponsiveImage,
	},
	g8ToaZVmj: {
		title: "Image 3",
		type: ControlType2.ResponsiveImage,
	},
	qO9woDsIE: {
		title: "Image 4",
		type: ControlType2.ResponsiveImage,
	},
	y0fX7xmZq: {
		title: "Image 5",
		type: ControlType2.ResponsiveImage,
	},
	ZrKNCUwGg: {
		title: "Image 6",
		type: ControlType2.ResponsiveImage,
	},
	YjoLglh7W: {
		title: "Image 7",
		type: ControlType2.ResponsiveImage,
	},
	kV0neR1DF: {
		title: "Image 8",
		type: ControlType2.ResponsiveImage,
	},
	qX5aJY0_l: {
		title: "1",
		type: ControlType2.EventHandler,
	},
	RthHlBIYj: {
		title: "2",
		type: ControlType2.EventHandler,
	},
	FfrO1KV0Q: {
		title: "3",
		type: ControlType2.EventHandler,
	},
	jR68EO0KP: {
		title: "4",
		type: ControlType2.EventHandler,
	},
	YLJ1H6SSA: {
		title: "5",
		type: ControlType2.EventHandler,
	},
});
addFonts2(
	Framerlk7KWV6ZS,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...GalleryNavigationItemFonts,
		...SVGFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/od8SOlu4F1n5iiC2pBBT/V6Fu3rSlBFwYSScOaLUy/Pk68TThW3.js
var GalleryNavigationCopyFonts = getFonts2(stdin_default4);
var GalleryImagesCopyFonts = getFonts2(stdin_default3);
var cycleOrder3 = [
	"tzeO_rm4J",
	"ytgfdrRuP",
	"iyUQrFVYH",
	"oW4Xn7jdj",
	"JuHe66f4c",
];
var serializationHash3 = "framer-XDUdu";
var variantClassNames3 = {
	iyUQrFVYH: "framer-v-ktz0kc",
	JuHe66f4c: "framer-v-lvbpbl",
	oW4Xn7jdj: "framer-v-1qv6job",
	tzeO_rm4J: "framer-v-1uk421e",
	ytgfdrRuP: "framer-v-1e0slz5",
};
function addPropertyOverrides3(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition13 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 650,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var toResponsiveImage3 = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion3(React3.Fragment);
var humanReadableVariantMap3 = {
	1: "tzeO_rm4J",
	2: "ytgfdrRuP",
	3: "iyUQrFVYH",
	4: "oW4Xn7jdj",
	5: "JuHe66f4c",
};
var getProps3 = ({
	background,
	height,
	id,
	image1,
	image2,
	image3,
	image4,
	image5,
	selector,
	width,
	...props
}) => {
	var _ref, _ref1, _ref2, _ref3, _humanReadableVariantMap_props_variant, _ref4;
	return {
		...props,
		AB57wm4vu: image5 !== null && image5 !== void 0 ? image5 : props.AB57wm4vu,
		aQnc30A6N:
			(_ref =
				selector !== null && selector !== void 0
					? selector
					: props.aQnc30A6N) !== null && _ref !== void 0
				? _ref
				: "var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
		DSJNh7kE4:
			(_ref1 =
				image2 !== null && image2 !== void 0 ? image2 : props.DSJNh7kE4) !==
				null && _ref1 !== void 0
				? _ref1
				: {
						src: "https://framerusercontent.com/images/sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp",
					},
		Jz5mRKP8b: image3 !== null && image3 !== void 0 ? image3 : props.Jz5mRKP8b,
		L3eYtamgf:
			(_ref2 =
				background !== null && background !== void 0
					? background
					: props.L3eYtamgf) !== null && _ref2 !== void 0
				? _ref2
				: "var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255))",
		NFYUL81vf:
			(_ref3 =
				image1 !== null && image1 !== void 0 ? image1 : props.NFYUL81vf) !==
				null && _ref3 !== void 0
				? _ref3
				: {
						src: "https://framerusercontent.com/images/lmFollwwBANyjurh7LnOrwRjzY.webp",
					},
		RROWsrtui: image4 !== null && image4 !== void 0 ? image4 : props.RROWsrtui,
		variant:
			(_ref4 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap3[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref4 !== void 0
				? _ref4
				: "tzeO_rm4J",
	};
};
var createLayoutDependency3 = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo3();
	const {
		style,
		className,
		layoutId,
		variant,
		L3eYtamgf,
		aQnc30A6N,
		NFYUL81vf,
		DSJNh7kE4,
		Jz5mRKP8b,
		RROWsrtui,
		AB57wm4vu,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		cycleOrder: cycleOrder3,
		defaultVariant: "tzeO_rm4J",
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const qX5aJY0_l1kwncvm = activeVariantCallback(async (...args) => {
		setVariant("tzeO_rm4J");
	});
	const RthHlBIYjz6buyu = activeVariantCallback(async (...args) => {
		setVariant("ytgfdrRuP");
	});
	const FfrO1KV0Q1qpuw7a = activeVariantCallback(async (...args) => {
		setVariant("iyUQrFVYH");
	});
	const jR68EO0KP1bhr7ut = activeVariantCallback(async (...args) => {
		setVariant("oW4Xn7jdj");
	});
	const YLJ1H6SSAs7yfhq = activeVariantCallback(async (...args) => {
		setVariant("JuHe66f4c");
	});
	const ref1 = React3.useRef(null);
	const defaultLayoutId = React3.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport3();
	return (
		<LayoutGroup3
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<motion3.div
						{...restProps}
						className={cx3(
							serializationHash3,
							...sharedStyleClassNames,
							"framer-1uk421e",
							className,
							classNames,
						)}
						data-framer-name={"1"}
						layoutDependency={layoutDependency}
						layoutId={"tzeO_rm4J"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							...style,
						}}
						{...addPropertyOverrides3(
							{
								iyUQrFVYH: {
									"data-framer-name": "3",
								},
								JuHe66f4c: {
									"data-framer-name": "5",
								},
								oW4Xn7jdj: {
									"data-framer-name": "4",
								},
								ytgfdrRuP: {
									"data-framer-name": "2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider2>
							<motion3.div
								className={"framer-1pybdtd-container"}
								layoutDependency={layoutDependency}
								layoutId={"UtUg6sWy4-container"}
								transformTemplate={transformTemplate1}
							>
								{_jsx3(stdin_default4, {
									cx33mnUE3: toResponsiveImage3(DSJNh7kE4),
									FfrO1KV0Q: FfrO1KV0Q1qpuw7a,
									FX_YoCLJm: toResponsiveImage3(NFYUL81vf),
									g8ToaZVmj: toResponsiveImage3(Jz5mRKP8b),
									height: "100%",
									id: "UtUg6sWy4",
									IqDVb43PR: aQnc30A6N,
									jR68EO0KP: jR68EO0KP1bhr7ut,
									layoutId: "UtUg6sWy4",
									qO9woDsIE: toResponsiveImage3(RROWsrtui),
									qX5aJY0_l: qX5aJY0_l1kwncvm,
									RthHlBIYj: RthHlBIYjz6buyu,
									variant: "uoqX6BTY6",
									width: "100%",
									XLzMbvsC3: L3eYtamgf,
									y0fX7xmZq: toResponsiveImage3(AB57wm4vu),
									YLJ1H6SSA: YLJ1H6SSAs7yfhq,
									...addPropertyOverrides3(
										{
											iyUQrFVYH: {
												variant: "laaWAmgqY",
											},
											JuHe66f4c: {
												variant: "j4VsBhjlb",
											},
											oW4Xn7jdj: {
												variant: "Aa8cd0l5f",
											},
											ytgfdrRuP: {
												variant: "wW3K0zpUj",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion3.div>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							width={`calc(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 2px)`}
						>
							<motion3.div
								className={"framer-3kqcyx-container"}
								layoutDependency={layoutDependency}
								layoutId={"W8AWjV1kO-container"}
							>
								{_jsx3(stdin_default3, {
									CQuyllWoH: toResponsiveImage3(DSJNh7kE4),
									CVqnpV02V: toResponsiveImage3(AB57wm4vu),
									E1VYOkQbB: toResponsiveImage3(Jz5mRKP8b),
									fo7liKqhn: toResponsiveImage3(RROWsrtui),
									ga3pCLb7N: toResponsiveImage3(NFYUL81vf),
									height: "100%",
									id: "W8AWjV1kO",
									layoutId: "W8AWjV1kO",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "LD918ZbGG",
									width: "100%",
									...addPropertyOverrides3(
										{
											iyUQrFVYH: {
												variant: "b8dLAwujk",
											},
											JuHe66f4c: {
												variant: "aRY8eKw8E",
											},
											oW4Xn7jdj: {
												variant: "pXFROP0zz",
											},
											ytgfdrRuP: {
												CQuyllWoH: void 0,
												CVqnpV02V: void 0,
												E1VYOkQbB: void 0,
												fo7liKqhn: void 0,
												ga3pCLb7N: void 0,
												variant: "zR0rvg3By",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion3.div>
						</ComponentViewportProvider2>
						<motion3.div
							className={"framer-1exl4ej"}
							data-framer-name={"Border"}
							layoutDependency={layoutDependency}
							layoutId={"wT72E8xMO"}
							style={{
								backgroundColor: aQnc30A6N,
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0.1,
							}}
						/>
					</motion3.div>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-XDUdu.framer-d2ul9w, .framer-XDUdu .framer-d2ul9w { display: block; }",
	".framer-XDUdu.framer-1uk421e { height: 449px; overflow: visible; position: relative; width: 656px; }",
	".framer-XDUdu .framer-1pybdtd-container { bottom: 0px; flex: none; height: auto; left: 50%; position: absolute; width: auto; z-index: 2; }",
	".framer-XDUdu .framer-3kqcyx-container { bottom: 82px; flex: none; left: 1px; position: absolute; right: 1px; top: 1px; z-index: 1; }",
	".framer-XDUdu .framer-1exl4ej { bottom: 81px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); }",
];
var FramerPk68TThW3 = withCSS3(Component3, css3, "framer-XDUdu");
var stdin_default5 = FramerPk68TThW3;
FramerPk68TThW3.displayName = "Gallery/Gallery Copy 2";
FramerPk68TThW3.defaultProps = {
	height: 449,
	width: 656,
};
addPropertyControls3(FramerPk68TThW3, {
	variant: {
		options: ["tzeO_rm4J", "ytgfdrRuP", "iyUQrFVYH", "oW4Xn7jdj", "JuHe66f4c"],
		optionTitles: ["1", "2", "3", "4", "5"],
		title: "Variant",
		type: ControlType3.Enum,
	},
	L3eYtamgf: {
		defaultValue:
			'var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255)) /* {"name":"12"} */',
		title: "Background",
		type: ControlType3.Color,
	},
	aQnc30A6N: {
		defaultValue:
			'var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5)) /* {"name":"1"} */',
		title: "Selector",
		type: ControlType3.Color,
	},
	NFYUL81vf: {
		__defaultAssetReference:
			"data:framer/asset-reference,lmFollwwBANyjurh7LnOrwRjzY.webp?originalFilename=blue-1.webp&preferredSize=full",
		title: "Image 1",
		type: ControlType3.ResponsiveImage,
	},
	DSJNh7kE4: {
		__defaultAssetReference:
			"data:framer/asset-reference,sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp?originalFilename=orange-1.webp&preferredSize=full",
		title: "Image 2",
		type: ControlType3.ResponsiveImage,
	},
	Jz5mRKP8b: {
		title: "Image 3",
		type: ControlType3.ResponsiveImage,
	},
	RROWsrtui: {
		title: "Image 4",
		type: ControlType3.ResponsiveImage,
	},
	AB57wm4vu: {
		title: "Image 5",
		type: ControlType3.ResponsiveImage,
	},
});
addFonts3(
	FramerPk68TThW3,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...GalleryNavigationCopyFonts,
		...GalleryImagesCopyFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:gallery/gallery-copy-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders GalleryCopy2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var gallery_copy_2_default = ComponentWithRoot;
export { gallery_copy_2_default as default };
