// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5393b9314a548245 "Osaka Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' // Variant
 * background?: string // Background
 * selector?: string // Selector
 * image1?: {src: string, srcSet?: string, alt?: string} // Image 1
 * image2?: {src: string, srcSet?: string, alt?: string} // Image 2
 * image3?: {src: string, srcSet?: string, alt?: string} // Image 3
 * image4?: {src: string, srcSet?: string, alt?: string} // Image 4
 * image5?: {src: string, srcSet?: string, alt?: string} // Image 5
 * image6?: {src: string, srcSet?: string, alt?: string} // Image 6
 * image7?: {src: string, srcSet?: string, alt?: string} // Image 7
 * image8?: {src: string, srcSet?: string, alt?: string} // Image 8
}} Props

 */
import {
	stdin_default as stdin_default3,
	stdin_default2 as stdin_default4,
} from "../chunks/chunk-NEL7CRMD.js";
import { stdin_default, stdin_default2 } from "../chunks/chunk-4L3SU7PC.js";
import { routes } from "../chunks/chunk-RIZBGR4E.js";

// virtual:gallery/gallery-copy
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/1I7jJLT4cl3kzx53YlTo/6RXTkTaqMEalh4CEODup/dcYvORQjL.js
import { jsx as _jsx3, jsxs as _jsxs3 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType3,
	cx as cx3,
	getFonts as getFonts2,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useVariantState as useVariantState3,
	withCSS as withCSS3,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion3,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React3 from "react";

// /:https://framerusercontent.com/modules/2C1XCW5oYMo2B0HiQJ9V/P3GJbLbQrn6xasudXzBa/JAdwOuuDw.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var GalleryNavigationItemFonts = getFonts(stdin_default2);
var SVGFonts = getFonts(stdin_default);
var GalleryNavigationItem1Fonts = getFonts(stdin_default4);
var GalleryNavigationItemCopyFonts = getFonts(stdin_default3);
var cycleOrder = [
	"zCfjaO_xP",
	"wGiKCC_11",
	"IZoa5hAvE",
	"TufNPY3TU",
	"pCQtPM1Yi",
	"DtJ6KHwtS",
	"z67oVgdVM",
	"CRWbeae02",
];
var serializationHash = "framer-vnlbx";
var variantClassNames = {
	CRWbeae02: "framer-v-jewlla",
	DtJ6KHwtS: "framer-v-aj4sjn",
	IZoa5hAvE: "framer-v-cfs7it",
	pCQtPM1Yi: "framer-v-poa1g0",
	TufNPY3TU: "framer-v-1tkihtz",
	wGiKCC_11: "framer-v-y97flb",
	z67oVgdVM: "framer-v-1vnpgkc",
	zCfjaO_xP: "framer-v-1r3u8de",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 650,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var isSet = (value) => {
	return value !== void 0 && value !== null && value !== "";
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	1: "zCfjaO_xP",
	2: "wGiKCC_11",
	3: "IZoa5hAvE",
	4: "TufNPY3TU",
	5: "pCQtPM1Yi",
	6: "DtJ6KHwtS",
	7: "z67oVgdVM",
	8: "CRWbeae02",
};
var getProps = ({
	_1,
	_2,
	_3,
	_4,
	_5,
	_6,
	_7,
	_8,
	background,
	height,
	id,
	image1,
	image2,
	image3,
	image4,
	image5,
	image6,
	image7,
	image8,
	selector,
	width,
	...props
}) => {
	var _ref,
		_ref1,
		_ref2,
		_ref3,
		_humanReadableVariantMap_props_variant,
		_ref4,
		_ref5;
	return {
		...props,
		cx33mnUE3:
			(_ref =
				image2 !== null && image2 !== void 0 ? image2 : props.cx33mnUE3) !==
				null && _ref !== void 0
				? _ref
				: {
						src: "https://framerusercontent.com/images/sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp?scale-down-to=512",
						srcSet:
							"https://framerusercontent.com/images/sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp?scale-down-to=512 512w,https://framerusercontent.com/images/sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp?scale-down-to=1024 1024w,https://framerusercontent.com/images/sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp 1456w",
					},
		FfrO1KV0Q: _3 !== null && _3 !== void 0 ? _3 : props.FfrO1KV0Q,
		FX_YoCLJm:
			(_ref1 =
				image1 !== null && image1 !== void 0 ? image1 : props.FX_YoCLJm) !==
				null && _ref1 !== void 0
				? _ref1
				: {
						src: "https://framerusercontent.com/images/lmFollwwBANyjurh7LnOrwRjzY.webp?scale-down-to=512",
						srcSet:
							"https://framerusercontent.com/images/lmFollwwBANyjurh7LnOrwRjzY.webp?scale-down-to=512 512w,https://framerusercontent.com/images/lmFollwwBANyjurh7LnOrwRjzY.webp?scale-down-to=1024 1024w,https://framerusercontent.com/images/lmFollwwBANyjurh7LnOrwRjzY.webp 1456w",
					},
		g8ToaZVmj:
			(_ref2 =
				image3 !== null && image3 !== void 0 ? image3 : props.g8ToaZVmj) !==
				null && _ref2 !== void 0
				? _ref2
				: {
						src: "https://framerusercontent.com/images/GXiUIOW4RqozMdPVVvDLHdh9o.png",
					},
		guL96G44I: _7 !== null && _7 !== void 0 ? _7 : props.guL96G44I,
		IqDVb43PR:
			(_ref3 =
				selector !== null && selector !== void 0
					? selector
					: props.IqDVb43PR) !== null && _ref3 !== void 0
				? _ref3
				: "var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255))",
		jR68EO0KP: _4 !== null && _4 !== void 0 ? _4 : props.jR68EO0KP,
		kV0neR1DF: image8 !== null && image8 !== void 0 ? image8 : props.kV0neR1DF,
		moyOFAv_J: _6 !== null && _6 !== void 0 ? _6 : props.moyOFAv_J,
		MvhWGEEJw: _8 !== null && _8 !== void 0 ? _8 : props.MvhWGEEJw,
		qO9woDsIE: image4 !== null && image4 !== void 0 ? image4 : props.qO9woDsIE,
		qX5aJY0_l: _1 !== null && _1 !== void 0 ? _1 : props.qX5aJY0_l,
		RthHlBIYj: _2 !== null && _2 !== void 0 ? _2 : props.RthHlBIYj,
		variant:
			(_ref4 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref4 !== void 0
				? _ref4
				: "zCfjaO_xP",
		XLzMbvsC3:
			(_ref5 =
				background !== null && background !== void 0
					? background
					: props.XLzMbvsC3) !== null && _ref5 !== void 0
				? _ref5
				: "var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
		y0fX7xmZq: image5 !== null && image5 !== void 0 ? image5 : props.y0fX7xmZq,
		YjoLglh7W: image7 !== null && image7 !== void 0 ? image7 : props.YjoLglh7W,
		YLJ1H6SSA: _5 !== null && _5 !== void 0 ? _5 : props.YLJ1H6SSA,
		ZrKNCUwGg: image6 !== null && image6 !== void 0 ? image6 : props.ZrKNCUwGg,
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		moyOFAv_J,
		guL96G44I,
		MvhWGEEJw,
		XLzMbvsC3,
		IqDVb43PR,
		FX_YoCLJm,
		cx33mnUE3,
		g8ToaZVmj,
		qO9woDsIE,
		y0fX7xmZq,
		ZrKNCUwGg,
		YjoLglh7W,
		kV0neR1DF,
		qX5aJY0_l,
		RthHlBIYj,
		FfrO1KV0Q,
		jR68EO0KP,
		YLJ1H6SSA,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "zCfjaO_xP",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const Na8yZDTE31yy3cb2 = activeVariantCallback(async (...args) => {
		if (qX5aJY0_l) {
			const res = await qX5aJY0_l(...args);
			if (res === false) return false;
		}
		setVariant("zCfjaO_xP");
	});
	const Na8yZDTE3tqf8az = activeVariantCallback(async (...args) => {
		if (RthHlBIYj) {
			const res = await RthHlBIYj(...args);
			if (res === false) return false;
		}
		setVariant("wGiKCC_11");
	});
	const Na8yZDTE3gphzko = activeVariantCallback(async (...args) => {
		if (FfrO1KV0Q) {
			const res = await FfrO1KV0Q(...args);
			if (res === false) return false;
		}
		setVariant("IZoa5hAvE");
	});
	const Na8yZDTE31j0imkk = activeVariantCallback(async (...args) => {
		if (jR68EO0KP) {
			const res = await jR68EO0KP(...args);
			if (res === false) return false;
		}
		setVariant("TufNPY3TU");
	});
	const Na8yZDTE3q84qb6 = activeVariantCallback(async (...args) => {
		if (YLJ1H6SSA) {
			const res = await YLJ1H6SSA(...args);
			if (res === false) return false;
		}
		setVariant("pCQtPM1Yi");
	});
	const Na8yZDTE31oxp0ny = activeVariantCallback(async (...args) => {
		if (moyOFAv_J) {
			const res = await moyOFAv_J(...args);
			if (res === false) return false;
		}
		setVariant("DtJ6KHwtS");
	});
	const Na8yZDTE3m9p9hi = activeVariantCallback(async (...args) => {
		if (guL96G44I) {
			const res = await guL96G44I(...args);
			if (res === false) return false;
		}
		setVariant("z67oVgdVM");
	});
	const Na8yZDTE318wqt3i = activeVariantCallback(async (...args) => {
		if (MvhWGEEJw) {
			const res = await MvhWGEEJw(...args);
			if (res === false) return false;
		}
		setVariant("CRWbeae02");
	});
	const ref1 = React.useRef(null);
	const visible = isSet(g8ToaZVmj);
	const visible1 = isSet(qO9woDsIE);
	const visible2 = isSet(y0fX7xmZq);
	const visible3 = isSet(ZrKNCUwGg);
	const visible4 = isSet(YjoLglh7W);
	const visible5 = isSet(kV0neR1DF);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1r3u8de",
							className,
							classNames,
						)}
						data-framer-name={"1"}
						layoutDependency={layoutDependency}
						layoutId={"zCfjaO_xP"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backgroundColor: XLzMbvsC3,
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							...style,
						}}
						{...addPropertyOverrides(
							{
								CRWbeae02: {
									"data-framer-name": "8",
								},
								DtJ6KHwtS: {
									"data-framer-name": "6",
								},
								IZoa5hAvE: {
									"data-framer-name": "3",
								},
								pCQtPM1Yi: {
									"data-framer-name": "5",
								},
								TufNPY3TU: {
									"data-framer-name": "4",
								},
								wGiKCC_11: {
									"data-framer-name": "2",
								},
								z67oVgdVM: {
									"data-framer-name": "7",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<motion.div
								className={"framer-u9kww9-container"}
								layoutDependency={layoutDependency}
								layoutId={"GJA6KspGs-container"}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "GJA6KspGs",
									layoutId: "GJA6KspGs",
									Na8yZDTE3: Na8yZDTE31yy3cb2,
									qorJ6sE5a: IqDVb43PR,
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "kGqWZo08u",
									width: "100%",
									ztRBQIg9r: toResponsiveImage(FX_YoCLJm),
									...addPropertyOverrides(
										{
											CRWbeae02: {
												variant: "JSBRhZ05q",
											},
											DtJ6KHwtS: {
												variant: "JSBRhZ05q",
											},
											IZoa5hAvE: {
												variant: "JSBRhZ05q",
											},
											pCQtPM1Yi: {
												variant: "JSBRhZ05q",
											},
											TufNPY3TU: {
												variant: "JSBRhZ05q",
											},
											wGiKCC_11: {
												variant: "JSBRhZ05q",
											},
											z67oVgdVM: {
												variant: "JSBRhZ05q",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider>
							<motion.div
								className={"framer-648koa-container"}
								layoutDependency={layoutDependency}
								layoutId={"X46BKtaX2-container"}
							>
								{_jsx(stdin_default2, {
									height: "100%",
									id: "X46BKtaX2",
									layoutId: "X46BKtaX2",
									Na8yZDTE3: Na8yZDTE3tqf8az,
									qorJ6sE5a: IqDVb43PR,
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "JSBRhZ05q",
									width: "100%",
									ztRBQIg9r: toResponsiveImage(cx33mnUE3),
									...addPropertyOverrides(
										{
											wGiKCC_11: {
												variant: "kGqWZo08u",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						{visible && (
							<ComponentViewportProvider>
								<motion.div
									className={"framer-ji1zay-container"}
									layoutDependency={layoutDependency}
									layoutId={"dYszRFTYv-container"}
								>
									{_jsx(stdin_default2, {
										height: "100%",
										id: "dYszRFTYv",
										layoutId: "dYszRFTYv",
										Na8yZDTE3: Na8yZDTE3gphzko,
										qorJ6sE5a: IqDVb43PR,
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "JSBRhZ05q",
										width: "100%",
										ztRBQIg9r: toResponsiveImage(g8ToaZVmj),
										...addPropertyOverrides(
											{
												IZoa5hAvE: {
													variant: "kGqWZo08u",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion.div>
							</ComponentViewportProvider>
						)}
						{visible1 && (
							<ComponentViewportProvider>
								<motion.div
									className={"framer-1hlo2yb-container"}
									layoutDependency={layoutDependency}
									layoutId={"thcYv41ID-container"}
								>
									{_jsx(stdin_default2, {
										height: "100%",
										id: "thcYv41ID",
										layoutId: "thcYv41ID",
										Na8yZDTE3: Na8yZDTE31j0imkk,
										qorJ6sE5a: IqDVb43PR,
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "JSBRhZ05q",
										width: "100%",
										ztRBQIg9r: toResponsiveImage(qO9woDsIE),
										...addPropertyOverrides(
											{
												TufNPY3TU: {
													variant: "kGqWZo08u",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion.div>
							</ComponentViewportProvider>
						)}
						{visible2 && (
							<ComponentViewportProvider>
								<motion.div
									className={"framer-yh1hfa-container"}
									layoutDependency={layoutDependency}
									layoutId={"tSCQZV8OU-container"}
								>
									{_jsx(stdin_default2, {
										height: "100%",
										id: "tSCQZV8OU",
										layoutId: "tSCQZV8OU",
										Na8yZDTE3: Na8yZDTE3q84qb6,
										qorJ6sE5a: IqDVb43PR,
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "JSBRhZ05q",
										width: "100%",
										ztRBQIg9r: toResponsiveImage(y0fX7xmZq),
										...addPropertyOverrides(
											{
												pCQtPM1Yi: {
													variant: "kGqWZo08u",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion.div>
							</ComponentViewportProvider>
						)}
						{visible3 && (
							<ComponentViewportProvider>
								<motion.div
									className={"framer-e9hinh-container"}
									layoutDependency={layoutDependency}
									layoutId={"kdgO_Fkoi-container"}
								>
									{_jsx(stdin_default2, {
										height: "100%",
										id: "kdgO_Fkoi",
										layoutId: "kdgO_Fkoi",
										Na8yZDTE3: Na8yZDTE31oxp0ny,
										qorJ6sE5a: IqDVb43PR,
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "JSBRhZ05q",
										width: "100%",
										ztRBQIg9r: toResponsiveImage(ZrKNCUwGg),
										...addPropertyOverrides(
											{
												DtJ6KHwtS: {
													variant: "kGqWZo08u",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion.div>
							</ComponentViewportProvider>
						)}
						{visible4 && (
							<ComponentViewportProvider>
								<motion.div
									className={"framer-cy99lw-container"}
									layoutDependency={layoutDependency}
									layoutId={"Y4S21aUbE-container"}
								>
									{_jsx(stdin_default2, {
										height: "100%",
										id: "Y4S21aUbE",
										layoutId: "Y4S21aUbE",
										Na8yZDTE3: Na8yZDTE3m9p9hi,
										qorJ6sE5a: IqDVb43PR,
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "JSBRhZ05q",
										width: "100%",
										ztRBQIg9r: toResponsiveImage(YjoLglh7W),
										...addPropertyOverrides(
											{
												z67oVgdVM: {
													variant: "kGqWZo08u",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion.div>
							</ComponentViewportProvider>
						)}
						{visible5 && (
							<ComponentViewportProvider>
								<motion.div
									className={"framer-pxi2p1-container"}
									layoutDependency={layoutDependency}
									layoutId={"YGzmq_yCb-container"}
								>
									{_jsx(stdin_default2, {
										height: "100%",
										id: "YGzmq_yCb",
										layoutId: "YGzmq_yCb",
										Na8yZDTE3: Na8yZDTE318wqt3i,
										qorJ6sE5a: IqDVb43PR,
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "JSBRhZ05q",
										width: "100%",
										ztRBQIg9r: toResponsiveImage(kV0neR1DF),
										...addPropertyOverrides(
											{
												CRWbeae02: {
													variant: "kGqWZo08u",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion.div>
							</ComponentViewportProvider>
						)}
						<motion.div
							className={"framer-1n24bxq"}
							data-framer-name={"Selector"}
							layoutDependency={layoutDependency}
							layoutId={"p_UjIMzJd"}
						>
							<motion.div
								className={"framer-18ldhm3"}
								data-framer-name={"Helper"}
								layoutDependency={layoutDependency}
								layoutId={"j8Wq6U9uY"}
							>
								<ComponentViewportProvider>
									<motion.div
										className={"framer-19jfab2-container"}
										layoutDependency={layoutDependency}
										layoutId={"OKnKSJLR8-container"}
									>
										{_jsx(stdin_default, {
											customColor: IqDVb43PR,
											customPadding: 0,
											customStrokeWidth: 2,
											customSvgCode:
												'<svg width="86" height="50" viewBox="0 0 86 50" fill="none" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" clip-rule="evenodd" d="M9.96341 0H76.0366C81.5731 0 86 4.48832 86 9.94983V40.0502C86 45.5117 81.5731 50 76.0366 50H9.96342C4.42691 50 0 45.5117 0 40.0502V9.94983C0 4.48832 4.42691 0 9.96341 0ZM9.96341 1.92308C5.54024 1.92308 1.95455 5.51678 1.95455 9.94983V40.0502C1.95455 44.4832 5.54024 48.0769 9.96342 48.0769H76.0366C80.4598 48.0769 84.0455 44.4832 84.0455 40.0502V9.94983C84.0455 5.51678 80.4598 1.92308 76.0366 1.92308H9.96341Z" fill="black"/> </svg>',
											height: "100%",
											id: "OKnKSJLR8",
											layoutId: "OKnKSJLR8",
											lineCap: "butt",
											lineJoin: "miter",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
										})}
									</motion.div>
								</ComponentViewportProvider>
							</motion.div>
							<ComponentViewportProvider width={"82px"}>
								<motion.div
									className={"framer-4r0t0-container"}
									layoutDependency={layoutDependency}
									layoutId={"oyg2zf2tu-container"}
									style={{
										opacity: 0,
									}}
								>
									{_jsx(stdin_default4, {
										height: "100%",
										id: "oyg2zf2tu",
										layoutId: "oyg2zf2tu",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "qmHLs_fes",
										width: "100%",
										ztRBQIg9r: toResponsiveImage(cx33mnUE3),
									})}
								</motion.div>
							</ComponentViewportProvider>
							<ComponentViewportProvider width={"82px"}>
								<motion.div
									className={"framer-ndy01v-container"}
									layoutDependency={layoutDependency}
									layoutId={"o8zMPP44Y-container"}
									style={{
										opacity: 0,
									}}
								>
									{_jsx(stdin_default3, {
										height: "100%",
										id: "o8zMPP44Y",
										layoutId: "o8zMPP44Y",
										qorJ6sE5a: "rgb(255, 255, 255)",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "GfhOzcuYK",
										width: "100%",
										ztRBQIg9r: toResponsiveImage(g8ToaZVmj),
									})}
								</motion.div>
							</ComponentViewportProvider>
							{visible1 && (
								<ComponentViewportProvider>
									<motion.div
										className={"framer-ladl5-container"}
										layoutDependency={layoutDependency}
										layoutId={"HZTUPpRW3-container"}
										style={{
											opacity: 0,
										}}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "HZTUPpRW3",
											layoutId: "HZTUPpRW3",
											qorJ6sE5a: "rgb(255, 255, 255)",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "JSBRhZ05q",
											width: "100%",
											ztRBQIg9r: toResponsiveImage(qO9woDsIE),
										})}
									</motion.div>
								</ComponentViewportProvider>
							)}
							{visible2 && (
								<ComponentViewportProvider>
									<motion.div
										className={"framer-ve6rsu-container"}
										layoutDependency={layoutDependency}
										layoutId={"SIcWBmnk5-container"}
										style={{
											opacity: 0,
										}}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "SIcWBmnk5",
											layoutId: "SIcWBmnk5",
											qorJ6sE5a: "rgb(255, 255, 255)",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "JSBRhZ05q",
											width: "100%",
											ztRBQIg9r: toResponsiveImage(y0fX7xmZq),
										})}
									</motion.div>
								</ComponentViewportProvider>
							)}
							{visible3 && (
								<ComponentViewportProvider>
									<motion.div
										className={"framer-1s7xaoh-container"}
										layoutDependency={layoutDependency}
										layoutId={"eByaw_AU0-container"}
										style={{
											opacity: 0,
										}}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "eByaw_AU0",
											layoutId: "eByaw_AU0",
											qorJ6sE5a: "rgb(255, 255, 255)",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "JSBRhZ05q",
											width: "100%",
											ztRBQIg9r: toResponsiveImage(ZrKNCUwGg),
										})}
									</motion.div>
								</ComponentViewportProvider>
							)}
							{visible4 && (
								<ComponentViewportProvider>
									<motion.div
										className={"framer-17qu98a-container"}
										layoutDependency={layoutDependency}
										layoutId={"dwViumyFN-container"}
										style={{
											opacity: 0,
										}}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "dwViumyFN",
											layoutId: "dwViumyFN",
											qorJ6sE5a: "rgb(255, 255, 255)",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "JSBRhZ05q",
											width: "100%",
											ztRBQIg9r: toResponsiveImage(YjoLglh7W),
										})}
									</motion.div>
								</ComponentViewportProvider>
							)}
							{visible5 && (
								<ComponentViewportProvider>
									<motion.div
										className={"framer-12dodrn-container"}
										layoutDependency={layoutDependency}
										layoutId={"A86iyoo2w-container"}
										style={{
											opacity: 0,
										}}
									>
										{_jsx(stdin_default2, {
											height: "100%",
											id: "A86iyoo2w",
											layoutId: "A86iyoo2w",
											qorJ6sE5a: "rgb(255, 255, 255)",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "JSBRhZ05q",
											width: "100%",
											ztRBQIg9r: toResponsiveImage(kV0neR1DF),
										})}
									</motion.div>
								</ComponentViewportProvider>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-vnlbx.framer-3wxxo3, .framer-vnlbx .framer-3wxxo3 { display: block; }",
	".framer-vnlbx.framer-1r3u8de { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; max-width: 380px; overflow: hidden; padding: 8px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-vnlbx .framer-u9kww9-container, .framer-vnlbx .framer-648koa-container, .framer-vnlbx .framer-ji1zay-container, .framer-vnlbx .framer-1hlo2yb-container, .framer-vnlbx .framer-yh1hfa-container, .framer-vnlbx .framer-e9hinh-container, .framer-vnlbx .framer-cy99lw-container, .framer-vnlbx .framer-pxi2p1-container { flex: none; height: 46px; position: relative; width: 82px; }",
	".framer-vnlbx .framer-1n24bxq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: 52px; justify-content: flex-start; left: 0px; overflow: visible; padding: 8px; pointer-events: none; position: absolute; right: 0px; top: calc(50.00000000000002% - 52px / 2); z-index: 2; }",
	".framer-vnlbx .framer-18ldhm3 { flex: none; height: 52px; overflow: visible; pointer-events: none; position: relative; width: 82px; }",
	".framer-vnlbx .framer-19jfab2-container { flex: none; height: 50px; left: calc(50.00000000000002% - 86px / 2); position: absolute; top: calc(50.00000000000002% - 50px / 2); width: 86px; z-index: 1; }",
	".framer-vnlbx .framer-4r0t0-container, .framer-vnlbx .framer-ndy01v-container, .framer-vnlbx .framer-ladl5-container, .framer-vnlbx .framer-ve6rsu-container, .framer-vnlbx .framer-1s7xaoh-container, .framer-vnlbx .framer-17qu98a-container, .framer-vnlbx .framer-12dodrn-container { flex: none; height: 46px; pointer-events: none; position: relative; width: 82px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-vnlbx.framer-1r3u8de, .framer-vnlbx .framer-1n24bxq { gap: 0px; } .framer-vnlbx.framer-1r3u8de > *, .framer-vnlbx .framer-1n24bxq > * { margin: 0px; margin-left: calc(4px / 2); margin-right: calc(4px / 2); } .framer-vnlbx.framer-1r3u8de > :first-child, .framer-vnlbx .framer-1n24bxq > :first-child { margin-left: 0px; } .framer-vnlbx.framer-1r3u8de > :last-child, .framer-vnlbx .framer-1n24bxq > :last-child { margin-right: 0px; } }",
	".framer-vnlbx.framer-v-y97flb .framer-18ldhm3, .framer-vnlbx.framer-v-cfs7it .framer-ndy01v-container, .framer-vnlbx.framer-v-1tkihtz .framer-ndy01v-container, .framer-vnlbx.framer-v-poa1g0 .framer-ndy01v-container, .framer-vnlbx.framer-v-aj4sjn .framer-ndy01v-container, .framer-vnlbx.framer-v-1vnpgkc .framer-ndy01v-container, .framer-vnlbx.framer-v-jewlla .framer-ndy01v-container { order: 1; }",
	".framer-vnlbx.framer-v-y97flb .framer-4r0t0-container, .framer-vnlbx.framer-v-cfs7it .framer-4r0t0-container, .framer-vnlbx.framer-v-1tkihtz .framer-4r0t0-container, .framer-vnlbx.framer-v-poa1g0 .framer-4r0t0-container, .framer-vnlbx.framer-v-aj4sjn .framer-4r0t0-container, .framer-vnlbx.framer-v-1vnpgkc .framer-4r0t0-container, .framer-vnlbx.framer-v-jewlla .framer-4r0t0-container { order: 0; }",
	".framer-vnlbx.framer-v-y97flb .framer-ndy01v-container, .framer-vnlbx.framer-v-cfs7it .framer-18ldhm3, .framer-vnlbx.framer-v-1tkihtz .framer-ladl5-container, .framer-vnlbx.framer-v-poa1g0 .framer-ladl5-container, .framer-vnlbx.framer-v-aj4sjn .framer-ladl5-container, .framer-vnlbx.framer-v-1vnpgkc .framer-ladl5-container, .framer-vnlbx.framer-v-jewlla .framer-ladl5-container { order: 2; }",
	".framer-vnlbx.framer-v-y97flb .framer-ladl5-container, .framer-vnlbx.framer-v-cfs7it .framer-ladl5-container, .framer-vnlbx.framer-v-1tkihtz .framer-18ldhm3, .framer-vnlbx.framer-v-poa1g0 .framer-ve6rsu-container, .framer-vnlbx.framer-v-aj4sjn .framer-ve6rsu-container, .framer-vnlbx.framer-v-1vnpgkc .framer-ve6rsu-container, .framer-vnlbx.framer-v-jewlla .framer-ve6rsu-container { order: 3; }",
	".framer-vnlbx.framer-v-y97flb .framer-ve6rsu-container, .framer-vnlbx.framer-v-cfs7it .framer-ve6rsu-container, .framer-vnlbx.framer-v-1tkihtz .framer-ve6rsu-container, .framer-vnlbx.framer-v-poa1g0 .framer-18ldhm3, .framer-vnlbx.framer-v-aj4sjn .framer-1s7xaoh-container, .framer-vnlbx.framer-v-1vnpgkc .framer-1s7xaoh-container, .framer-vnlbx.framer-v-jewlla .framer-1s7xaoh-container { order: 4; }",
	".framer-vnlbx.framer-v-y97flb .framer-1s7xaoh-container, .framer-vnlbx.framer-v-cfs7it .framer-1s7xaoh-container, .framer-vnlbx.framer-v-1tkihtz .framer-1s7xaoh-container, .framer-vnlbx.framer-v-poa1g0 .framer-1s7xaoh-container, .framer-vnlbx.framer-v-aj4sjn .framer-18ldhm3, .framer-vnlbx.framer-v-1vnpgkc .framer-17qu98a-container, .framer-vnlbx.framer-v-jewlla .framer-17qu98a-container { order: 5; }",
	".framer-vnlbx.framer-v-y97flb .framer-17qu98a-container, .framer-vnlbx.framer-v-cfs7it .framer-17qu98a-container, .framer-vnlbx.framer-v-1tkihtz .framer-17qu98a-container, .framer-vnlbx.framer-v-poa1g0 .framer-17qu98a-container, .framer-vnlbx.framer-v-aj4sjn .framer-17qu98a-container, .framer-vnlbx.framer-v-1vnpgkc .framer-18ldhm3, .framer-vnlbx.framer-v-jewlla .framer-12dodrn-container { order: 6; }",
	".framer-vnlbx.framer-v-y97flb .framer-12dodrn-container, .framer-vnlbx.framer-v-cfs7it .framer-12dodrn-container, .framer-vnlbx.framer-v-1tkihtz .framer-12dodrn-container, .framer-vnlbx.framer-v-poa1g0 .framer-12dodrn-container, .framer-vnlbx.framer-v-aj4sjn .framer-12dodrn-container, .framer-vnlbx.framer-v-1vnpgkc .framer-12dodrn-container, .framer-vnlbx.framer-v-jewlla .framer-18ldhm3 { order: 7; }",
	".framer-vnlbx.framer-v-poa1g0.framer-1r3u8de, .framer-vnlbx.framer-v-poa1g0 .framer-1n24bxq, .framer-vnlbx.framer-v-aj4sjn.framer-1r3u8de, .framer-vnlbx.framer-v-aj4sjn .framer-1n24bxq, .framer-vnlbx.framer-v-1vnpgkc.framer-1r3u8de, .framer-vnlbx.framer-v-1vnpgkc .framer-1n24bxq, .framer-vnlbx.framer-v-jewlla.framer-1r3u8de, .framer-vnlbx.framer-v-jewlla .framer-1n24bxq { justify-content: flex-end; }",
];
var FramerJAdwOuuDw = withCSS(Component, css, "framer-vnlbx");
var stdin_default5 = FramerJAdwOuuDw;
FramerJAdwOuuDw.displayName = "Gallery/Navigation";
FramerJAdwOuuDw.defaultProps = {
	height: 62,
	width: 270,
};
addPropertyControls(FramerJAdwOuuDw, {
	variant: {
		options: [
			"zCfjaO_xP",
			"wGiKCC_11",
			"IZoa5hAvE",
			"TufNPY3TU",
			"pCQtPM1Yi",
			"DtJ6KHwtS",
			"z67oVgdVM",
			"CRWbeae02",
		],
		optionTitles: ["1", "2", "3", "4", "5", "6", "7", "8"],
		title: "Variant",
		type: ControlType.Enum,
	},
	moyOFAv_J: {
		title: "6",
		type: ControlType.EventHandler,
	},
	guL96G44I: {
		title: "7",
		type: ControlType.EventHandler,
	},
	MvhWGEEJw: {
		title: "8",
		type: ControlType.EventHandler,
	},
	XLzMbvsC3: {
		defaultValue:
			'var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5)) /* {"name":"1"} */',
		title: "Background",
		type: ControlType.Color,
	},
	IqDVb43PR: {
		defaultValue:
			'var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255)) /* {"name":"12"} */',
		title: "Selector",
		type: ControlType.Color,
	},
	FX_YoCLJm: {
		__defaultAssetReference:
			"data:framer/asset-reference,lmFollwwBANyjurh7LnOrwRjzY.webp?originalFilename=blue-1.webp&preferredSize=auto",
		title: "Image 1",
		type: ControlType.ResponsiveImage,
	},
	cx33mnUE3: {
		__defaultAssetReference:
			"data:framer/asset-reference,sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp?originalFilename=orange-1.webp&preferredSize=auto",
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
	g8ToaZVmj: {
		__defaultAssetReference:
			"data:framer/asset-reference,GXiUIOW4RqozMdPVVvDLHdh9o.png?originalFilename=Slider.png&preferredSize=full",
		title: "Image 3",
		type: ControlType.ResponsiveImage,
	},
	qO9woDsIE: {
		title: "Image 4",
		type: ControlType.ResponsiveImage,
	},
	y0fX7xmZq: {
		title: "Image 5",
		type: ControlType.ResponsiveImage,
	},
	ZrKNCUwGg: {
		title: "Image 6",
		type: ControlType.ResponsiveImage,
	},
	YjoLglh7W: {
		title: "Image 7",
		type: ControlType.ResponsiveImage,
	},
	kV0neR1DF: {
		title: "Image 8",
		type: ControlType.ResponsiveImage,
	},
	qX5aJY0_l: {
		title: "1",
		type: ControlType.EventHandler,
	},
	RthHlBIYj: {
		title: "2",
		type: ControlType.EventHandler,
	},
	FfrO1KV0Q: {
		title: "3",
		type: ControlType.EventHandler,
	},
	jR68EO0KP: {
		title: "4",
		type: ControlType.EventHandler,
	},
	YLJ1H6SSA: {
		title: "5",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerJAdwOuuDw,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...GalleryNavigationItemFonts,
		...SVGFonts,
		...GalleryNavigationItem1Fonts,
		...GalleryNavigationItemCopyFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/mdjjNZjEAP2UkZEuQeAO/M3TRzypGSGC345mGwaEz/qb0cx57_8.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	Image,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
var cycleOrder2 = [
	"B4Zm2gDBa",
	"D8oVt0bNP",
	"aZbEhSUpr",
	"KatLUUqvn",
	"iIporNq3s",
	"QLwOSRE2j",
	"H5XCN6rEx",
	"t2i7U1LpI",
];
var serializationHash2 = "framer-CKciX";
var variantClassNames2 = {
	aZbEhSUpr: "framer-v-1xxsjni",
	B4Zm2gDBa: "framer-v-1bf93m3",
	D8oVt0bNP: "framer-v-1abjl9d",
	H5XCN6rEx: "framer-v-1thhayd",
	iIporNq3s: "framer-v-h7o4xe",
	KatLUUqvn: "framer-v-1eri44p",
	QLwOSRE2j: "framer-v-1wuwc75",
	t2i7U1LpI: "framer-v-vegxuf",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition12 = {
	duration: 0,
	type: "tween",
};
var toResponsiveImage2 = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2(React2.Fragment);
var humanReadableVariantMap2 = {
	1: "B4Zm2gDBa",
	2: "D8oVt0bNP",
	3: "aZbEhSUpr",
	4: "KatLUUqvn",
	5: "iIporNq3s",
	6: "QLwOSRE2j",
	7: "H5XCN6rEx",
	8: "t2i7U1LpI",
};
var getProps2 = ({
	height,
	id,
	image1,
	image2,
	image3,
	image4,
	image5,
	image6,
	image7,
	image8,
	width,
	...props
}) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		CQuyllWoH: image2 !== null && image2 !== void 0 ? image2 : props.CQuyllWoH,
		CVqnpV02V: image5 !== null && image5 !== void 0 ? image5 : props.CVqnpV02V,
		E1VYOkQbB: image3 !== null && image3 !== void 0 ? image3 : props.E1VYOkQbB,
		fo7liKqhn: image4 !== null && image4 !== void 0 ? image4 : props.fo7liKqhn,
		ga3pCLb7N: image1 !== null && image1 !== void 0 ? image1 : props.ga3pCLb7N,
		Hbt1_Qqr7: image8 !== null && image8 !== void 0 ? image8 : props.Hbt1_Qqr7,
		NOOYR5UCo: image6 !== null && image6 !== void 0 ? image6 : props.NOOYR5UCo,
		oVr0ArdS6: image7 !== null && image7 !== void 0 ? image7 : props.oVr0ArdS6,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap2[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "B4Zm2gDBa",
	};
};
var createLayoutDependency2 = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className,
		layoutId,
		variant,
		ga3pCLb7N,
		CQuyllWoH,
		E1VYOkQbB,
		fo7liKqhn,
		CVqnpV02V,
		NOOYR5UCo,
		oVr0ArdS6,
		Hbt1_Qqr7,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "B4Zm2gDBa",
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const ref1 = React2.useRef(null);
	const defaultLayoutId = React2.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport2();
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						className={cx2(
							serializationHash2,
							...sharedStyleClassNames,
							"framer-1bf93m3",
							className,
							classNames,
						)}
						data-framer-name={"1"}
						layoutDependency={layoutDependency}
						layoutId={"B4Zm2gDBa"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							...style,
						}}
						{...addPropertyOverrides2(
							{
								aZbEhSUpr: {
									"data-framer-name": "3",
								},
								D8oVt0bNP: {
									"data-framer-name": "2",
								},
								H5XCN6rEx: {
									"data-framer-name": "7",
								},
								iIporNq3s: {
									"data-framer-name": "5",
								},
								KatLUUqvn: {
									"data-framer-name": "4",
								},
								QLwOSRE2j: {
									"data-framer-name": "6",
								},
								t2i7U1LpI: {
									"data-framer-name": "8",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								sizes:
									(componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.width) || "100vw",
								...toResponsiveImage2(ga3pCLb7N),
							}}
							className={"framer-14mqyoa"}
							data-framer-name={"1"}
							layoutDependency={layoutDependency}
							layoutId={"lTB5zhJAq"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 1,
							}}
							variants={{
								aZbEhSUpr: {
									opacity: 0,
								},
								D8oVt0bNP: {
									opacity: 0,
								},
								H5XCN6rEx: {
									opacity: 0,
								},
								iIporNq3s: {
									opacity: 0,
								},
								KatLUUqvn: {
									opacity: 0,
								},
								QLwOSRE2j: {
									opacity: 0,
								},
								t2i7U1LpI: {
									opacity: 0,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								sizes:
									(componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.width) || "100vw",
								...toResponsiveImage2(CQuyllWoH),
							}}
							className={"framer-14my3gn"}
							data-framer-name={"2"}
							layoutDependency={layoutDependency}
							layoutId={"Vp6OvCOqh"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0,
							}}
							variants={{
								D8oVt0bNP: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								sizes:
									(componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.width) || "100vw",
								...toResponsiveImage2(E1VYOkQbB),
							}}
							className={"framer-1bu3np5"}
							data-framer-name={"3"}
							layoutDependency={layoutDependency}
							layoutId={"IL24nd5q2"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0,
							}}
							variants={{
								aZbEhSUpr: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								sizes:
									(componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.width) || "100vw",
								...toResponsiveImage2(fo7liKqhn),
							}}
							className={"framer-1tgyb9d"}
							data-framer-name={"4"}
							layoutDependency={layoutDependency}
							layoutId={"hF70RIYna"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0,
							}}
							variants={{
								KatLUUqvn: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								sizes:
									(componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.width) || "100vw",
								...toResponsiveImage2(CVqnpV02V),
							}}
							className={"framer-rrzr5s"}
							data-framer-name={"5"}
							layoutDependency={layoutDependency}
							layoutId={"IsHsvmSHA"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0,
							}}
							variants={{
								iIporNq3s: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								sizes:
									(componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.width) || "100vw",
								...toResponsiveImage2(NOOYR5UCo),
							}}
							className={"framer-1cfjeol"}
							data-framer-name={"6"}
							layoutDependency={layoutDependency}
							layoutId={"alas_eqNC"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0,
							}}
							variants={{
								QLwOSRE2j: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								sizes:
									(componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.width) || "100vw",
								...toResponsiveImage2(oVr0ArdS6),
							}}
							className={"framer-xop81j"}
							data-framer-name={"7"}
							layoutDependency={layoutDependency}
							layoutId={"vw7eWKaGK"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0,
							}}
							variants={{
								H5XCN6rEx: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								sizes:
									(componentViewport === null || componentViewport === void 0
										? void 0
										: componentViewport.width) || "100vw",
								...toResponsiveImage2(Hbt1_Qqr7),
							}}
							className={"framer-micx8a"}
							data-framer-name={"8"}
							layoutDependency={layoutDependency}
							layoutId={"TFuEI1lfN"}
							style={{
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0,
							}}
							variants={{
								t2i7U1LpI: {
									opacity: 1,
								},
							}}
						/>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-CKciX.framer-jpce58, .framer-CKciX .framer-jpce58 { display: block; }",
	".framer-CKciX.framer-1bf93m3 { height: 368px; overflow: hidden; position: relative; width: 656px; will-change: var(--framer-will-change-override, transform); }",
	".framer-CKciX .framer-14mqyoa, .framer-CKciX .framer-14my3gn, .framer-CKciX .framer-1bu3np5, .framer-CKciX .framer-1tgyb9d, .framer-CKciX .framer-rrzr5s, .framer-CKciX .framer-1cfjeol, .framer-CKciX .framer-xop81j, .framer-CKciX .framer-micx8a { bottom: 0px; flex: none; left: 0px; overflow: visible; pointer-events: none; position: absolute; right: 0px; top: 0px; }",
];
var Framerqb0cx57_8 = withCSS2(Component2, css2, "framer-CKciX");
var stdin_default6 = Framerqb0cx57_8;
Framerqb0cx57_8.displayName = "Gallery/Images";
Framerqb0cx57_8.defaultProps = {
	height: 368,
	width: 656,
};
addPropertyControls2(Framerqb0cx57_8, {
	variant: {
		options: [
			"B4Zm2gDBa",
			"D8oVt0bNP",
			"aZbEhSUpr",
			"KatLUUqvn",
			"iIporNq3s",
			"QLwOSRE2j",
			"H5XCN6rEx",
			"t2i7U1LpI",
		],
		optionTitles: ["1", "2", "3", "4", "5", "6", "7", "8"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	ga3pCLb7N: {
		title: "Image 1",
		type: ControlType2.ResponsiveImage,
	},
	CQuyllWoH: {
		title: "Image 2",
		type: ControlType2.ResponsiveImage,
	},
	E1VYOkQbB: {
		title: "Image 3",
		type: ControlType2.ResponsiveImage,
	},
	fo7liKqhn: {
		title: "Image 4",
		type: ControlType2.ResponsiveImage,
	},
	CVqnpV02V: {
		title: "Image 5",
		type: ControlType2.ResponsiveImage,
	},
	NOOYR5UCo: {
		title: "Image 6",
		type: ControlType2.ResponsiveImage,
	},
	oVr0ArdS6: {
		title: "Image 7",
		type: ControlType2.ResponsiveImage,
	},
	Hbt1_Qqr7: {
		title: "Image 8",
		type: ControlType2.ResponsiveImage,
	},
});
addFonts2(
	Framerqb0cx57_8,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/1I7jJLT4cl3kzx53YlTo/6RXTkTaqMEalh4CEODup/dcYvORQjL.js
var GalleryNavigationFonts = getFonts2(stdin_default5);
var GalleryImagesFonts = getFonts2(stdin_default6);
var cycleOrder3 = [
	"GzdTiRiHd",
	"anIgw3XEJ",
	"muoEvP3io",
	"rApP5FCQN",
	"mTJiGDkCT",
	"A6_VLFvtV",
	"Bs_ZSVw6c",
	"MEWN0SOu3",
];
var serializationHash3 = "framer-KUfJO";
var variantClassNames3 = {
	A6_VLFvtV: "framer-v-de0805",
	anIgw3XEJ: "framer-v-nw6rtq",
	Bs_ZSVw6c: "framer-v-1ynk9sg",
	GzdTiRiHd: "framer-v-hkl0xv",
	MEWN0SOu3: "framer-v-1r1tupv",
	mTJiGDkCT: "framer-v-1miid13",
	muoEvP3io: "framer-v-1wdnall",
	rApP5FCQN: "framer-v-13tcht",
};
function addPropertyOverrides3(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition13 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 650,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var toResponsiveImage3 = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition3 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext3);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion3(React3.Fragment);
var humanReadableVariantMap3 = {
	1: "GzdTiRiHd",
	2: "anIgw3XEJ",
	3: "muoEvP3io",
	4: "rApP5FCQN",
	5: "mTJiGDkCT",
	6: "A6_VLFvtV",
	7: "Bs_ZSVw6c",
	8: "MEWN0SOu3",
};
var getProps3 = ({
	background,
	height,
	id,
	image1,
	image2,
	image3,
	image4,
	image5,
	image6,
	image7,
	image8,
	selector,
	width,
	...props
}) => {
	var _ref, _ref1, _ref2, _ref3, _humanReadableVariantMap_props_variant, _ref4;
	return {
		...props,
		AB57wm4vu: image5 !== null && image5 !== void 0 ? image5 : props.AB57wm4vu,
		aQnc30A6N:
			(_ref =
				selector !== null && selector !== void 0
					? selector
					: props.aQnc30A6N) !== null && _ref !== void 0
				? _ref
				: "var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
		DSJNh7kE4:
			(_ref1 =
				image2 !== null && image2 !== void 0 ? image2 : props.DSJNh7kE4) !==
				null && _ref1 !== void 0
				? _ref1
				: {
						src: "https://framerusercontent.com/images/sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp",
					},
		iVBKtZsnr: image6 !== null && image6 !== void 0 ? image6 : props.iVBKtZsnr,
		Jz5mRKP8b: image3 !== null && image3 !== void 0 ? image3 : props.Jz5mRKP8b,
		L3eYtamgf:
			(_ref2 =
				background !== null && background !== void 0
					? background
					: props.L3eYtamgf) !== null && _ref2 !== void 0
				? _ref2
				: "var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255))",
		LqdxvB4A5: image7 !== null && image7 !== void 0 ? image7 : props.LqdxvB4A5,
		NFYUL81vf:
			(_ref3 =
				image1 !== null && image1 !== void 0 ? image1 : props.NFYUL81vf) !==
				null && _ref3 !== void 0
				? _ref3
				: {
						src: "https://framerusercontent.com/images/lmFollwwBANyjurh7LnOrwRjzY.webp",
					},
		RROWsrtui: image4 !== null && image4 !== void 0 ? image4 : props.RROWsrtui,
		variant:
			(_ref4 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap3[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref4 !== void 0
				? _ref4
				: "GzdTiRiHd",
		Vc2MsyiJ4: image8 !== null && image8 !== void 0 ? image8 : props.Vc2MsyiJ4,
	};
};
var createLayoutDependency3 = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo3();
	const {
		style,
		className,
		layoutId,
		variant,
		L3eYtamgf,
		aQnc30A6N,
		NFYUL81vf,
		DSJNh7kE4,
		Jz5mRKP8b,
		RROWsrtui,
		AB57wm4vu,
		iVBKtZsnr,
		LqdxvB4A5,
		Vc2MsyiJ4,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		cycleOrder: cycleOrder3,
		defaultVariant: "GzdTiRiHd",
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const moyOFAv_J1x2ec94 = activeVariantCallback(async (...args) => {
		setVariant("A6_VLFvtV");
	});
	const guL96G44I14gk5rv = activeVariantCallback(async (...args) => {
		setVariant("Bs_ZSVw6c");
	});
	const MvhWGEEJw1ig5cau = activeVariantCallback(async (...args) => {
		setVariant("MEWN0SOu3");
	});
	const qX5aJY0_lv9irt7 = activeVariantCallback(async (...args) => {
		setVariant("GzdTiRiHd");
	});
	const RthHlBIYja34slb = activeVariantCallback(async (...args) => {
		setVariant("anIgw3XEJ");
	});
	const FfrO1KV0Q1ldpubg = activeVariantCallback(async (...args) => {
		setVariant("muoEvP3io");
	});
	const jR68EO0KPvsj8wa = activeVariantCallback(async (...args) => {
		setVariant("rApP5FCQN");
	});
	const YLJ1H6SSA85ahgs = activeVariantCallback(async (...args) => {
		setVariant("mTJiGDkCT");
	});
	const ref1 = React3.useRef(null);
	const defaultLayoutId = React3.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport3();
	return (
		<LayoutGroup3
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<motion3.div
						{...restProps}
						className={cx3(
							serializationHash3,
							...sharedStyleClassNames,
							"framer-hkl0xv",
							className,
							classNames,
						)}
						data-framer-name={"1"}
						layoutDependency={layoutDependency}
						layoutId={"GzdTiRiHd"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides3(
							{
								A6_VLFvtV: {
									"data-framer-name": "6",
								},
								anIgw3XEJ: {
									"data-framer-name": "2",
								},
								Bs_ZSVw6c: {
									"data-framer-name": "7",
								},
								MEWN0SOu3: {
									"data-framer-name": "8",
								},
								mTJiGDkCT: {
									"data-framer-name": "5",
								},
								muoEvP3io: {
									"data-framer-name": "3",
								},
								rApP5FCQN: {
									"data-framer-name": "4",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider2>
							<motion3.div
								className={"framer-1hbiyk8-container"}
								layoutDependency={layoutDependency}
								layoutId={"s8fs4sHmc-container"}
								transformTemplate={transformTemplate1}
							>
								{_jsx3(stdin_default5, {
									cx33mnUE3: toResponsiveImage3(DSJNh7kE4),
									FfrO1KV0Q: FfrO1KV0Q1ldpubg,
									FX_YoCLJm: toResponsiveImage3(NFYUL81vf),
									g8ToaZVmj: toResponsiveImage3(Jz5mRKP8b),
									guL96G44I: guL96G44I14gk5rv,
									height: "100%",
									id: "s8fs4sHmc",
									IqDVb43PR: aQnc30A6N,
									jR68EO0KP: jR68EO0KPvsj8wa,
									kV0neR1DF: toResponsiveImage3(Vc2MsyiJ4),
									layoutId: "s8fs4sHmc",
									moyOFAv_J: moyOFAv_J1x2ec94,
									MvhWGEEJw: MvhWGEEJw1ig5cau,
									qO9woDsIE: toResponsiveImage3(RROWsrtui),
									qX5aJY0_l: qX5aJY0_lv9irt7,
									RthHlBIYj: RthHlBIYja34slb,
									variant: "zCfjaO_xP",
									width: "100%",
									XLzMbvsC3: L3eYtamgf,
									y0fX7xmZq: toResponsiveImage3(AB57wm4vu),
									YjoLglh7W: toResponsiveImage3(LqdxvB4A5),
									YLJ1H6SSA: YLJ1H6SSA85ahgs,
									ZrKNCUwGg: toResponsiveImage3(iVBKtZsnr),
									...addPropertyOverrides3(
										{
											A6_VLFvtV: {
												variant: "DtJ6KHwtS",
											},
											anIgw3XEJ: {
												variant: "wGiKCC_11",
											},
											Bs_ZSVw6c: {
												variant: "z67oVgdVM",
											},
											MEWN0SOu3: {
												variant: "CRWbeae02",
											},
											mTJiGDkCT: {
												variant: "pCQtPM1Yi",
											},
											muoEvP3io: {
												variant: "IZoa5hAvE",
											},
											rApP5FCQN: {
												variant: "TufNPY3TU",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion3.div>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							width={`calc(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 2px)`}
						>
							<motion3.div
								className={"framer-y1pyb8-container"}
								layoutDependency={layoutDependency}
								layoutId={"czVcFcUc_-container"}
							>
								{_jsx3(stdin_default6, {
									CQuyllWoH: toResponsiveImage3(DSJNh7kE4),
									CVqnpV02V: toResponsiveImage3(AB57wm4vu),
									E1VYOkQbB: toResponsiveImage3(Jz5mRKP8b),
									fo7liKqhn: toResponsiveImage3(RROWsrtui),
									ga3pCLb7N: toResponsiveImage3(NFYUL81vf),
									Hbt1_Qqr7: toResponsiveImage3(Vc2MsyiJ4),
									height: "100%",
									id: "czVcFcUc_",
									layoutId: "czVcFcUc_",
									NOOYR5UCo: toResponsiveImage3(iVBKtZsnr),
									oVr0ArdS6: toResponsiveImage3(LqdxvB4A5),
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "B4Zm2gDBa",
									width: "100%",
									...addPropertyOverrides3(
										{
											A6_VLFvtV: {
												variant: "QLwOSRE2j",
											},
											anIgw3XEJ: {
												variant: "D8oVt0bNP",
											},
											Bs_ZSVw6c: {
												variant: "H5XCN6rEx",
											},
											MEWN0SOu3: {
												variant: "t2i7U1LpI",
											},
											mTJiGDkCT: {
												variant: "iIporNq3s",
											},
											muoEvP3io: {
												variant: "aZbEhSUpr",
											},
											rApP5FCQN: {
												variant: "KatLUUqvn",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion3.div>
						</ComponentViewportProvider2>
					</motion3.div>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-KUfJO.framer-dh1emx, .framer-KUfJO .framer-dh1emx { display: block; }",
	".framer-KUfJO.framer-hkl0xv { height: 449px; overflow: visible; position: relative; width: 656px; }",
	".framer-KUfJO .framer-1hbiyk8-container { bottom: 0px; flex: none; height: auto; left: 50%; position: absolute; width: auto; z-index: 2; }",
	".framer-KUfJO .framer-y1pyb8-container { bottom: 82px; flex: none; left: 1px; position: absolute; right: 1px; top: 1px; z-index: 1; }",
];
var FramerdcYvORQjL = withCSS3(Component3, css3, "framer-KUfJO");
var stdin_default7 = FramerdcYvORQjL;
FramerdcYvORQjL.displayName = "Gallery/Gallery Copy";
FramerdcYvORQjL.defaultProps = {
	height: 449,
	width: 656,
};
addPropertyControls3(FramerdcYvORQjL, {
	variant: {
		options: [
			"GzdTiRiHd",
			"anIgw3XEJ",
			"muoEvP3io",
			"rApP5FCQN",
			"mTJiGDkCT",
			"A6_VLFvtV",
			"Bs_ZSVw6c",
			"MEWN0SOu3",
		],
		optionTitles: ["1", "2", "3", "4", "5", "6", "7", "8"],
		title: "Variant",
		type: ControlType3.Enum,
	},
	L3eYtamgf: {
		defaultValue:
			'var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255)) /* {"name":"12"} */',
		title: "Background",
		type: ControlType3.Color,
	},
	aQnc30A6N: {
		defaultValue:
			'var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5)) /* {"name":"1"} */',
		title: "Selector",
		type: ControlType3.Color,
	},
	NFYUL81vf: {
		__defaultAssetReference:
			"data:framer/asset-reference,lmFollwwBANyjurh7LnOrwRjzY.webp?originalFilename=blue-1.webp&preferredSize=full",
		title: "Image 1",
		type: ControlType3.ResponsiveImage,
	},
	DSJNh7kE4: {
		__defaultAssetReference:
			"data:framer/asset-reference,sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp?originalFilename=orange-1.webp&preferredSize=full",
		title: "Image 2",
		type: ControlType3.ResponsiveImage,
	},
	Jz5mRKP8b: {
		title: "Image 3",
		type: ControlType3.ResponsiveImage,
	},
	RROWsrtui: {
		title: "Image 4",
		type: ControlType3.ResponsiveImage,
	},
	AB57wm4vu: {
		title: "Image 5",
		type: ControlType3.ResponsiveImage,
	},
	iVBKtZsnr: {
		title: "Image 6",
		type: ControlType3.ResponsiveImage,
	},
	LqdxvB4A5: {
		title: "Image 7",
		type: ControlType3.ResponsiveImage,
	},
	Vc2MsyiJ4: {
		title: "Image 8",
		type: ControlType3.ResponsiveImage,
	},
});
addFonts3(
	FramerdcYvORQjL,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...GalleryNavigationFonts,
		...GalleryImagesFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:gallery/gallery-copy
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default7, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders GalleryCopyFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default7}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default7);
var gallery_copy_default = ComponentWithRoot;
export { gallery_copy_default as default };
