// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5393b9314a548245 "Osaka Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' // Variant
 * background?: string // Background
 * selector?: string // Selector
 * image1?: {src: string, srcSet?: string, alt?: string} // Image 1
 * image2?: {src: string, srcSet?: string, alt?: string} // Image 2
 * image3?: {src: string, srcSet?: string, alt?: string} // Image 3
 * image4?: {src: string, srcSet?: string, alt?: string} // Image 4
 * image5?: {src: string, srcSet?: string, alt?: string} // Image 5
 * image6?: {src: string, srcSet?: string, alt?: string} // Image 6
 * image7?: {src: string, srcSet?: string, alt?: string} // Image 7
 * image8?: {src: string, srcSet?: string, alt?: string} // Image 8
}} Props

 */
import { stdin_default, stdin_default2 } from "../chunks/chunk-B3UOTL4Q.js";
import "../chunks/chunk-4L3SU7PC.js";
import { routes } from "../chunks/chunk-RIZBGR4E.js";

// virtual:gallery/gallery
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/dDyeEQkrGuxSARyuTZX3/IVZwlvBLeRDzR0adXlLr/w2JEVwLQn.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var GalleryNavigationFonts = getFonts(stdin_default2);
var GalleryImagesFonts = getFonts(stdin_default);
var cycleOrder = [
	"Xpps3uGpB",
	"CLlPR3gkQ",
	"liVJidwNq",
	"bOI8b2Eyu",
	"qAk2cpfhV",
	"D22Kku1OC",
	"FWDmf3gim",
	"yc0A0jmE7",
];
var serializationHash = "framer-xYmAn";
var variantClassNames = {
	bOI8b2Eyu: "framer-v-qfntr5",
	CLlPR3gkQ: "framer-v-zj7bwc",
	D22Kku1OC: "framer-v-3cznr0",
	FWDmf3gim: "framer-v-pkqf0p",
	liVJidwNq: "framer-v-1jgrpbl",
	qAk2cpfhV: "framer-v-fww46",
	Xpps3uGpB: "framer-v-p04c9f",
	yc0A0jmE7: "framer-v-jmo0q7",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 650,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	1: "Xpps3uGpB",
	2: "CLlPR3gkQ",
	3: "liVJidwNq",
	4: "bOI8b2Eyu",
	5: "qAk2cpfhV",
	6: "D22Kku1OC",
	7: "FWDmf3gim",
	8: "yc0A0jmE7",
};
var getProps = ({
	background,
	height,
	id,
	image1,
	image2,
	image3,
	image4,
	image5,
	image6,
	image7,
	image8,
	selector,
	width,
	...props
}) => {
	var _ref, _ref1, _ref2, _ref3, _humanReadableVariantMap_props_variant, _ref4;
	return {
		...props,
		AB57wm4vu: image5 !== null && image5 !== void 0 ? image5 : props.AB57wm4vu,
		aQnc30A6N:
			(_ref =
				selector !== null && selector !== void 0
					? selector
					: props.aQnc30A6N) !== null && _ref !== void 0
				? _ref
				: "var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
		DSJNh7kE4:
			(_ref1 =
				image2 !== null && image2 !== void 0 ? image2 : props.DSJNh7kE4) !==
				null && _ref1 !== void 0
				? _ref1
				: {
						src: "https://framerusercontent.com/images/sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp?scale-down-to=1024",
						srcSet:
							"https://framerusercontent.com/images/sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp?scale-down-to=512 512w,https://framerusercontent.com/images/sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp?scale-down-to=1024 1024w,https://framerusercontent.com/images/sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp 1456w",
					},
		iVBKtZsnr: image6 !== null && image6 !== void 0 ? image6 : props.iVBKtZsnr,
		Jz5mRKP8b: image3 !== null && image3 !== void 0 ? image3 : props.Jz5mRKP8b,
		L3eYtamgf:
			(_ref2 =
				background !== null && background !== void 0
					? background
					: props.L3eYtamgf) !== null && _ref2 !== void 0
				? _ref2
				: "var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255))",
		LqdxvB4A5: image7 !== null && image7 !== void 0 ? image7 : props.LqdxvB4A5,
		NFYUL81vf:
			(_ref3 =
				image1 !== null && image1 !== void 0 ? image1 : props.NFYUL81vf) !==
				null && _ref3 !== void 0
				? _ref3
				: {
						src: "https://framerusercontent.com/images/lmFollwwBANyjurh7LnOrwRjzY.webp?scale-down-to=1024",
						srcSet:
							"https://framerusercontent.com/images/lmFollwwBANyjurh7LnOrwRjzY.webp?scale-down-to=512 512w,https://framerusercontent.com/images/lmFollwwBANyjurh7LnOrwRjzY.webp?scale-down-to=1024 1024w,https://framerusercontent.com/images/lmFollwwBANyjurh7LnOrwRjzY.webp 1456w",
					},
		RROWsrtui: image4 !== null && image4 !== void 0 ? image4 : props.RROWsrtui,
		variant:
			(_ref4 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref4 !== void 0
				? _ref4
				: "Xpps3uGpB",
		Vc2MsyiJ4: image8 !== null && image8 !== void 0 ? image8 : props.Vc2MsyiJ4,
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		L3eYtamgf,
		aQnc30A6N,
		NFYUL81vf,
		DSJNh7kE4,
		Jz5mRKP8b,
		RROWsrtui,
		AB57wm4vu,
		iVBKtZsnr,
		LqdxvB4A5,
		Vc2MsyiJ4,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Xpps3uGpB",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const moyOFAv_J1nqh3pq = activeVariantCallback(async (...args) => {
		setVariant("D22Kku1OC");
	});
	const guL96G44Il5bf23 = activeVariantCallback(async (...args) => {
		setVariant("FWDmf3gim");
	});
	const MvhWGEEJw11aqu38 = activeVariantCallback(async (...args) => {
		setVariant("yc0A0jmE7");
	});
	const qX5aJY0_lxyapjm = activeVariantCallback(async (...args) => {
		setVariant("Xpps3uGpB");
	});
	const RthHlBIYj1oo619q = activeVariantCallback(async (...args) => {
		setVariant("CLlPR3gkQ");
	});
	const FfrO1KV0Qrqv20j = activeVariantCallback(async (...args) => {
		setVariant("liVJidwNq");
	});
	const jR68EO0KP1j80akm = activeVariantCallback(async (...args) => {
		setVariant("bOI8b2Eyu");
	});
	const YLJ1H6SSAn8ll7q = activeVariantCallback(async (...args) => {
		setVariant("qAk2cpfhV");
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-p04c9f",
							className,
							classNames,
						)}
						data-framer-name={"1"}
						layoutDependency={layoutDependency}
						layoutId={"Xpps3uGpB"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							...style,
						}}
						{...addPropertyOverrides(
							{
								bOI8b2Eyu: {
									"data-framer-name": "4",
								},
								CLlPR3gkQ: {
									"data-framer-name": "2",
								},
								D22Kku1OC: {
									"data-framer-name": "6",
								},
								FWDmf3gim: {
									"data-framer-name": "7",
								},
								liVJidwNq: {
									"data-framer-name": "3",
								},
								qAk2cpfhV: {
									"data-framer-name": "5",
								},
								yc0A0jmE7: {
									"data-framer-name": "8",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<motion.div
								className={"framer-wy762p-container"}
								layoutDependency={layoutDependency}
								layoutId={"YOHPpy2CW-container"}
								transformTemplate={transformTemplate1}
							>
								{_jsx(stdin_default2, {
									cx33mnUE3: toResponsiveImage(DSJNh7kE4),
									FfrO1KV0Q: FfrO1KV0Qrqv20j,
									FX_YoCLJm: toResponsiveImage(NFYUL81vf),
									g8ToaZVmj: toResponsiveImage(Jz5mRKP8b),
									guL96G44I: guL96G44Il5bf23,
									height: "100%",
									id: "YOHPpy2CW",
									IqDVb43PR: aQnc30A6N,
									jR68EO0KP: jR68EO0KP1j80akm,
									kV0neR1DF: toResponsiveImage(Vc2MsyiJ4),
									layoutId: "YOHPpy2CW",
									moyOFAv_J: moyOFAv_J1nqh3pq,
									MvhWGEEJw: MvhWGEEJw11aqu38,
									qO9woDsIE: toResponsiveImage(RROWsrtui),
									qX5aJY0_l: qX5aJY0_lxyapjm,
									RthHlBIYj: RthHlBIYj1oo619q,
									variant: "sWviQKIxH",
									width: "100%",
									XLzMbvsC3: L3eYtamgf,
									y0fX7xmZq: toResponsiveImage(AB57wm4vu),
									YjoLglh7W: toResponsiveImage(LqdxvB4A5),
									YLJ1H6SSA: YLJ1H6SSAn8ll7q,
									ZrKNCUwGg: toResponsiveImage(iVBKtZsnr),
									...addPropertyOverrides(
										{
											bOI8b2Eyu: {
												variant: "MsmC3_wur",
											},
											CLlPR3gkQ: {
												variant: "PhT7IzTRL",
											},
											D22Kku1OC: {
												variant: "Y0OZVA34l",
											},
											FWDmf3gim: {
												variant: "BKuMeoHms",
											},
											liVJidwNq: {
												variant: "fvK3TlZwl",
											},
											qAk2cpfhV: {
												variant: "Ko10hC4oY",
											},
											yc0A0jmE7: {
												variant: "tSm0HX6eu",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider>
							<motion.div
								className={"framer-1ey3pn-container"}
								layoutDependency={layoutDependency}
								layoutId={"zfiLDXc7Y-container"}
							>
								{_jsx(stdin_default, {
									CQuyllWoH: toResponsiveImage(DSJNh7kE4),
									CVqnpV02V: toResponsiveImage(AB57wm4vu),
									E1VYOkQbB: toResponsiveImage(Jz5mRKP8b),
									fo7liKqhn: toResponsiveImage(RROWsrtui),
									ga3pCLb7N: toResponsiveImage(NFYUL81vf),
									Hbt1_Qqr7: toResponsiveImage(Vc2MsyiJ4),
									height: "100%",
									id: "zfiLDXc7Y",
									layoutId: "zfiLDXc7Y",
									NOOYR5UCo: toResponsiveImage(iVBKtZsnr),
									oVr0ArdS6: toResponsiveImage(LqdxvB4A5),
									style: {
										height: "100%",
										width: "100%",
									},
									variant: "ImEi6PjDn",
									width: "100%",
									...addPropertyOverrides(
										{
											bOI8b2Eyu: {
												variant: "yERmuL08l",
											},
											CLlPR3gkQ: {
												variant: "exsKPrxTp",
											},
											D22Kku1OC: {
												variant: "AnKogmQvf",
											},
											FWDmf3gim: {
												variant: "OS7AzClgs",
											},
											liVJidwNq: {
												variant: "M0t0grOF6",
											},
											qAk2cpfhV: {
												variant: "vZamyttoR",
											},
											yc0A0jmE7: {
												variant: "pX66JCaED",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-4sg42p"}
							data-framer-name={"Border"}
							layoutDependency={layoutDependency}
							layoutId={"L8qO9fwFb"}
							style={{
								backgroundColor: aQnc30A6N,
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
								opacity: 0.1,
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xYmAn.framer-1o3xx47, .framer-xYmAn .framer-1o3xx47 { display: block; }",
	".framer-xYmAn.framer-p04c9f { height: 368px; overflow: visible; position: relative; width: 656px; }",
	".framer-xYmAn .framer-wy762p-container { bottom: -44px; flex: none; height: auto; left: 50%; position: absolute; width: auto; z-index: 2; }",
	".framer-xYmAn .framer-1ey3pn-container { bottom: 1px; flex: none; left: 1px; position: absolute; right: 1px; top: 1px; z-index: 1; }",
	".framer-xYmAn .framer-4sg42p { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-override, transform); }",
];
var Framerw2JEVwLQn = withCSS(Component, css, "framer-xYmAn");
var stdin_default3 = Framerw2JEVwLQn;
Framerw2JEVwLQn.displayName = "Gallery/Gallery";
Framerw2JEVwLQn.defaultProps = {
	height: 368,
	width: 656,
};
addPropertyControls(Framerw2JEVwLQn, {
	variant: {
		options: [
			"Xpps3uGpB",
			"CLlPR3gkQ",
			"liVJidwNq",
			"bOI8b2Eyu",
			"qAk2cpfhV",
			"D22Kku1OC",
			"FWDmf3gim",
			"yc0A0jmE7",
		],
		optionTitles: ["1", "2", "3", "4", "5", "6", "7", "8"],
		title: "Variant",
		type: ControlType.Enum,
	},
	L3eYtamgf: {
		defaultValue:
			'var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255)) /* {"name":"12"} */',
		title: "Background",
		type: ControlType.Color,
	},
	aQnc30A6N: {
		defaultValue:
			'var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5)) /* {"name":"1"} */',
		title: "Selector",
		type: ControlType.Color,
	},
	NFYUL81vf: {
		__defaultAssetReference:
			"data:framer/asset-reference,lmFollwwBANyjurh7LnOrwRjzY.webp?originalFilename=blue-1.webp&preferredSize=auto",
		title: "Image 1",
		type: ControlType.ResponsiveImage,
	},
	DSJNh7kE4: {
		__defaultAssetReference:
			"data:framer/asset-reference,sQNMTjOuH5HwpdcYsQ1Mini7TGk.webp?originalFilename=orange-1.webp&preferredSize=auto",
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
	Jz5mRKP8b: {
		title: "Image 3",
		type: ControlType.ResponsiveImage,
	},
	RROWsrtui: {
		title: "Image 4",
		type: ControlType.ResponsiveImage,
	},
	AB57wm4vu: {
		title: "Image 5",
		type: ControlType.ResponsiveImage,
	},
	iVBKtZsnr: {
		title: "Image 6",
		type: ControlType.ResponsiveImage,
	},
	LqdxvB4A5: {
		title: "Image 7",
		type: ControlType.ResponsiveImage,
	},
	Vc2MsyiJ4: {
		title: "Image 8",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	Framerw2JEVwLQn,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...GalleryNavigationFonts,
		...GalleryImagesFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:gallery/gallery
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders GalleryFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var gallery_default = ComponentWithRoot;
export { gallery_default as default };
