// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5393b9314a548245 "Osaka Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * avatar?: {src: string, srcSet?: string, alt?: string} // Avatar
 * name?: string // Name
 * job?: string // Job
 * border?: undefined // Border
 * align?: 'Start' | 'Center' | 'End' // Align
 * align2?: 'Start' | 'Center' | 'End' // Align 2
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-2ALKGF66.js";
import { routes } from "./chunks/chunk-RIZBGR4E.js";

// virtual:avatar-card-magical-team
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/le6BojJedj1oVVNGl97t/Fv4Y8pVYS2eCrEnblMvK/rwLgLuB30.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["ssWG7TZPh"];
var serializationHash = "framer-TsUzg";
var variantClassNames = {
	ssWG7TZPh: "framer-v-16z6xvz",
};
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableEnumMap = {
	Center: "center",
	End: "flex-end",
	Start: "flex-start",
};
var getProps = ({
	align,
	align2,
	avatar,
	border,
	height,
	id,
	job,
	name1,
	width,
	...props
}) => {
	var _humanReadableEnumMap_align,
		_ref,
		_ref1,
		_ref2,
		_humanReadableEnumMap_align2,
		_ref3,
		_ref4,
		_ref5,
		_ref6;
	return {
		...props,
		GdXud7b4t:
			(_ref1 =
				(_ref =
					(_humanReadableEnumMap_align = humanReadableEnumMap[align]) !==
						null && _humanReadableEnumMap_align !== void 0
						? _humanReadableEnumMap_align
						: align) !== null && _ref !== void 0
					? _ref
					: props.GdXud7b4t) !== null && _ref1 !== void 0
				? _ref1
				: "center",
		LqXTK2RYT:
			(_ref2 =
				border !== null && border !== void 0 ? border : props.LqXTK2RYT) !==
				null && _ref2 !== void 0
				? _ref2
				: {
						borderBottomWidth: 0,
						borderColor:
							'var(--token-a441ca95-8d02-4c53-b63e-38f78f03c624, rgb(233, 237, 241)) /* {"name":"Border / Normal [50]"} */',
						borderLeftWidth: 0,
						borderRightWidth: 1,
						borderStyle: "solid",
						borderTopWidth: 1,
					},
		QNRhZ78Nw:
			(_ref4 =
				(_ref3 =
					(_humanReadableEnumMap_align2 = humanReadableEnumMap[align2]) !==
						null && _humanReadableEnumMap_align2 !== void 0
						? _humanReadableEnumMap_align2
						: align2) !== null && _ref3 !== void 0
					? _ref3
					: props.QNRhZ78Nw) !== null && _ref4 !== void 0
				? _ref4
				: "center",
		SfCkVykRi:
			(_ref5 = name1 !== null && name1 !== void 0 ? name1 : props.SfCkVykRi) !==
				null && _ref5 !== void 0
				? _ref5
				: "Umutcan Eyriyer",
		WoWk3EmQw:
			(_ref6 = job !== null && job !== void 0 ? job : props.WoWk3EmQw) !==
				null && _ref6 !== void 0
				? _ref6
				: "Digital Product Designer.",
		xKBEftWmb: avatar !== null && avatar !== void 0 ? avatar : props.xKBEftWmb,
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		xKBEftWmb,
		SfCkVykRi,
		WoWk3EmQw,
		LqXTK2RYT,
		GdXud7b4t,
		QNRhZ78Nw,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ssWG7TZPh",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	var _LqXTK2RYT_borderBottomWidth,
		_LqXTK2RYT_borderLeftWidth,
		_LqXTK2RYT_borderRightWidth,
		_LqXTK2RYT_borderTopWidth;
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-16z6xvz",
							className2,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"ssWG7TZPh"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width": `${(_LqXTK2RYT_borderBottomWidth = LqXTK2RYT.borderBottomWidth) !== null && _LqXTK2RYT_borderBottomWidth !== void 0 ? _LqXTK2RYT_borderBottomWidth : LqXTK2RYT.borderWidth}px`,
							"--border-color": LqXTK2RYT.borderColor,
							"--border-left-width": `${(_LqXTK2RYT_borderLeftWidth = LqXTK2RYT.borderLeftWidth) !== null && _LqXTK2RYT_borderLeftWidth !== void 0 ? _LqXTK2RYT_borderLeftWidth : LqXTK2RYT.borderWidth}px`,
							"--border-right-width": `${(_LqXTK2RYT_borderRightWidth = LqXTK2RYT.borderRightWidth) !== null && _LqXTK2RYT_borderRightWidth !== void 0 ? _LqXTK2RYT_borderRightWidth : LqXTK2RYT.borderWidth}px`,
							"--border-style": LqXTK2RYT.borderStyle,
							"--border-top-width": `${(_LqXTK2RYT_borderTopWidth = LqXTK2RYT.borderTopWidth) !== null && _LqXTK2RYT_borderTopWidth !== void 0 ? _LqXTK2RYT_borderTopWidth : LqXTK2RYT.borderWidth}px`,
							"--jgckhy": GdXud7b4t,
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
							}}
							className={"framer-jyjgm"}
							data-framer-name={"Employee Avatar"}
							layoutDependency={layoutDependency}
							layoutId={"Wt2WiBNFC"}
							style={{
								borderBottomLeftRadius: 60,
								borderBottomRightRadius: 60,
								borderTopLeftRadius: 60,
								borderTopRightRadius: 60,
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									sizes: "72px",
									...toResponsiveImage(xKBEftWmb),
								}}
								className={"framer-1fv6us7"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"D9LrRcqZI"}
							/>
						</Image>
						<motion.div
							className={"framer-g67bnt"}
							data-framer-name={"Frame 72"}
							layoutDependency={layoutDependency}
							layoutId={"SB6nPmGK8"}
							style={{
								"--16jwctm": QNRhZ78Nw,
							}}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1g2jr5u"}
								data-framer-name={"Umutcan Eyriyer"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Xv_eWYemr"}
								style={{
									"--extracted-gdpscs":
										"var(--token-e2b7c12a-f254-4034-80bb-3aca0e10bf19, rgb(13, 13, 18))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={SfCkVykRi}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h1
										className={"framer-styles-preset-1gh6fhc"}
										data-styles-preset={"wOLsulpos"}
										style={{
											"--framer-text-color":
												"var(--extracted-gdpscs, var(--token-e2b7c12a-f254-4034-80bb-3aca0e10bf19, rgb(13, 13, 18)))",
										}}
									>
										{"Umutcan Eyriyer"}
									</motion.h1>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1trq9ym"}
								data-framer-name={"product designer."}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Uqq85Ps6V"}
								style={{
									"--extracted-gdpscs":
										"var(--token-60964137-f0a1-41aa-8abf-3664a329e249, rgb(102, 109, 128))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={WoWk3EmQw}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h1
										className={"framer-styles-preset-1gh6fhc"}
										data-styles-preset={"wOLsulpos"}
										style={{
											"--framer-text-color":
												"var(--extracted-gdpscs, var(--token-60964137-f0a1-41aa-8abf-3664a329e249, rgb(102, 109, 128)))",
										}}
									>
										{"Digital Product Designer."}
									</motion.h1>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-TsUzg.framer-1x7i38k, .framer-TsUzg .framer-1x7i38k { display: block; }",
	".framer-TsUzg.framer-16z6xvz { align-content: var(--jgckhy); align-items: var(--jgckhy); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 32px; position: relative; width: 384px; }",
	".framer-TsUzg .framer-jyjgm { flex: none; height: 72px; overflow: hidden; position: relative; width: 72px; will-change: var(--framer-will-change-override, transform); }",
	".framer-TsUzg .framer-1fv6us7 { aspect-ratio: 0.6746987951807228 / 1; bottom: -25px; flex: none; left: 0px; position: absolute; top: -9px; width: var(--framer-aspect-ratio-supported, 72px); }",
	".framer-TsUzg .framer-g67bnt { align-content: var(--16jwctm); align-items: var(--16jwctm); display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-TsUzg .framer-1g2jr5u, .framer-TsUzg .framer-1trq9ym { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-TsUzg.framer-16z6xvz, .framer-TsUzg .framer-g67bnt { gap: 0px; } .framer-TsUzg.framer-16z6xvz > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-TsUzg.framer-16z6xvz > :first-child, .framer-TsUzg .framer-g67bnt > :first-child { margin-top: 0px; } .framer-TsUzg.framer-16z6xvz > :last-child, .framer-TsUzg .framer-g67bnt > :last-child { margin-bottom: 0px; } .framer-TsUzg .framer-g67bnt > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } }",
	...css,
	'.framer-TsUzg[data-border="true"]::after, .framer-TsUzg [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerrwLgLuB30 = withCSS(Component, css2, "framer-TsUzg");
var stdin_default = FramerrwLgLuB30;
FramerrwLgLuB30.displayName = "Avatar Card [Magical Team]";
FramerrwLgLuB30.defaultProps = {
	height: 208,
	width: 384,
};
addPropertyControls(FramerrwLgLuB30, {
	xKBEftWmb: {
		title: "Avatar",
		type: ControlType.ResponsiveImage,
	},
	SfCkVykRi: {
		defaultValue: "Umutcan Eyriyer",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	WoWk3EmQw: {
		defaultValue: "Digital Product Designer.",
		displayTextArea: false,
		title: "Job",
		type: ControlType.String,
	},
	LqXTK2RYT: {
		defaultValue: {
			borderBottomWidth: 0,
			borderColor:
				'var(--token-a441ca95-8d02-4c53-b63e-38f78f03c624, rgb(233, 237, 241)) /* {"name":"Border / Normal [50]"} */',
			borderLeftWidth: 0,
			borderRightWidth: 1,
			borderStyle: "solid",
			borderTopWidth: 1,
		},
		title: "Border",
		type: ControlType.Border,
	},
	GdXud7b4t: {
		defaultValue: "center",
		options: ["flex-start", "center", "flex-end"],
		optionTitles: ["Start", "Center", "End"],
		title: "Align",
		type: ControlType.Enum,
	},
	QNRhZ78Nw: {
		defaultValue: "center",
		options: ["flex-start", "center", "flex-end"],
		optionTitles: ["Start", "Center", "End"],
		title: "Align 2",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerrwLgLuB30,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:avatar-card-magical-team
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AvatarCardMagicalTeamFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var avatar_card_magical_team_default = ComponentWithRoot;
export { avatar_card_magical_team_default as default };
