// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5393b9314a548245 "Osaka Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * imageLeft?: {src: string, srcSet?: string, alt?: string} // Image-Left
 * imageRight?: {src: string, srcSet?: string, alt?: string} // Image-Right
 * iconRight?: boolean // Icon-Right
 * iconLeft?: boolean // Icon-Left
 * title?: string // Title
}} Props

 */
import { routes } from "./chunks/chunk-RIZBGR4E.js";

// virtual:buttons-ghost
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/4pQ4uzMrpScJFGMDTPvm/iYxzvWhSum7hy5WKALHM/fAGKBobJE.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Image,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";

// /:https://framerusercontent.com/modules/VIG7VxOwkdy4gexbhxvX/qQ9AIglLXtQmCQ3vAdIn/I04wxwwIQ.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Switzer-regular",
	"FS;Switzer-bold",
	"FS;Switzer-bold italic",
	"FS;Switzer-italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Switzer",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/BLNB4FAQFNK56DWWNF7PMGTCOTZHOEII/ST3WKSSDMBK2MIQQO3MAVYWLF4FTOLFV/6IN5WOLRCYP4G4MOCOHOMXNON6Q7MDAR.woff2",
				weight: "400",
			},
			{
				family: "Switzer",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/HBNTRIISA5MEXGL5WPYI7CV2HIWTDV3Q/YDPDINVT673XLXNSTMLG4JNCZZMVVNPN/Y7SCNZJOT2MW5ADSGOFLDGH4TNL4JCQY.woff2",
				weight: "700",
			},
			{
				family: "Switzer",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/LVPXCMXCWY3V7PSXRMGRQUJDAS2DT47E/BPEVRT2HG7PPVVUS7A67MZQQZW6LR6A5/A7AS3UPAGLC7MDVC67SBNTE5FGF2Z2RG.woff2",
				weight: "700",
			},
			{
				family: "Switzer",
				source: "fontshare",
				style: "italic",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/XVUY2PHYBA6KMN4RMEMJPHQSTKCQ267G/UICOQA6KCSHFOSCPYDVVDNNCDKYFXHJB/O34WRFYO7JNWEBBA2LRV2XYRUSYXYDKH.woff2",
				weight: "400",
			},
		],
	},
];
var css = [
	'.framer-9yVZc .framer-styles-preset-1v1rg9h:not(.rich-text-wrapper), .framer-9yVZc .framer-styles-preset-1v1rg9h.rich-text-wrapper h3 { --framer-font-family: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-bold-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-family-italic: "Switzer", "Switzer Placeholder", sans-serif; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.2px; --framer-line-height: 22px; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: #333333; --framer-text-decoration: none; --framer-text-transform: none; }',
];
var className = "framer-9yVZc";

// /:https://framerusercontent.com/modules/4pQ4uzMrpScJFGMDTPvm/iYxzvWhSum7hy5WKALHM/fAGKBobJE.js
var enabledGestures = {
	aZP543yhR: {
		hover: true,
	},
};
var cycleOrder = ["aZP543yhR"];
var serializationHash = "framer-KasFE";
var variantClassNames = {
	aZP543yhR: "framer-v-swrw9a",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var getProps = ({
	height,
	iconLeft,
	iconRight,
	id,
	imageLeft,
	imageRight,
	title,
	width,
	...props
}) => {
	var _ref, _ref1, _ref2, _ref3, _ref4;
	return {
		...props,
		aXo20rNiT:
			(_ref =
				iconLeft !== null && iconLeft !== void 0
					? iconLeft
					: props.aXo20rNiT) !== null && _ref !== void 0
				? _ref
				: true,
		bCHVikJAV:
			(_ref1 =
				imageRight !== null && imageRight !== void 0
					? imageRight
					: props.bCHVikJAV) !== null && _ref1 !== void 0
				? _ref1
				: {
						src: "https://framerusercontent.com/images/m34iBIKYEYLNuIWIy8F8pi0uo.svg",
					},
		H7SbZkGtw:
			(_ref2 =
				imageLeft !== null && imageLeft !== void 0
					? imageLeft
					: props.H7SbZkGtw) !== null && _ref2 !== void 0
				? _ref2
				: {
						src: "https://framerusercontent.com/images/R7H2r6TtI15RajTvXbuZc99aLIc.svg",
					},
		iK9Mx1VvZ:
			(_ref3 =
				iconRight !== null && iconRight !== void 0
					? iconRight
					: props.iK9Mx1VvZ) !== null && _ref3 !== void 0
				? _ref3
				: true,
		sFDdZDiqV:
			(_ref4 = title !== null && title !== void 0 ? title : props.sFDdZDiqV) !==
				null && _ref4 !== void 0
				? _ref4
				: "Back to Case Studies",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		H7SbZkGtw,
		bCHVikJAV,
		iK9Mx1VvZ,
		aXo20rNiT,
		sFDdZDiqV,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "aZP543yhR",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={{
							webPageId: "IzSwFrr9l",
						}}
					>
						<motion.a
							{...restProps}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-swrw9a", className2, classNames)} framer-switoo`}
							data-border={true}
							data-framer-name={"Variant 1"}
							layoutDependency={layoutDependency}
							layoutId={"aZP543yhR"}
							onHoverEnd={() =>
								setGestureState({
									isHovered: false,
								})
							}
							onHoverStart={() =>
								setGestureState({
									isHovered: true,
								})
							}
							onTap={() =>
								setGestureState({
									isPressed: false,
								})
							}
							onTapCancel={() =>
								setGestureState({
									isPressed: false,
								})
							}
							onTapStart={() =>
								setGestureState({
									isPressed: true,
								})
							}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								"--border-bottom-width": "0px",
								"--border-color": "rgb(233, 237, 241)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
								borderBottomLeftRadius: 40,
								borderBottomRightRadius: 40,
								borderTopLeftRadius: 40,
								borderTopRightRadius: 40,
								...style,
							}}
							{...addPropertyOverrides(
								{
									"aZP543yhR-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							{aXo20rNiT && (
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 24,
										intrinsicWidth: 24,
										pixelHeight: 24,
										pixelWidth: 24,
										sizes: "24px",
										...toResponsiveImage(H7SbZkGtw),
									}}
									className={"framer-1i93kz1"}
									data-framer-name={"Arrow-Right"}
									layoutDependency={layoutDependency}
									layoutId={"K7HJzrUcl"}
								/>
							)}
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1buqc1n"}
								data-framer-name={"Book a schedule"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"rXNVxfop1"}
								style={{
									"--framer-paragraph-spacing": "0px",
								}}
								text={sFDdZDiqV}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-1v1rg9h"}
										data-styles-preset={"I04wxwwIQ"}
									>
										{"Back to Case Studies"}
									</motion.h3>
								</React.Fragment>
							</RichText>
							{iK9Mx1VvZ && (
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 24,
										intrinsicWidth: 24,
										pixelHeight: 24,
										pixelWidth: 24,
										sizes: "24px",
										...toResponsiveImage(bCHVikJAV),
									}}
									className={"framer-zaj681"}
									data-framer-name={"Arrow-Right"}
									layoutDependency={layoutDependency}
									layoutId={"dw12c8ILM"}
								/>
							)}
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-KasFE.framer-switoo, .framer-KasFE .framer-switoo { display: block; }",
	".framer-KasFE.framer-swrw9a { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: 48px; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-KasFE .framer-1i93kz1, .framer-KasFE .framer-zaj681 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 24px); overflow: hidden; position: relative; width: 24px; }",
	".framer-KasFE .framer-1buqc1n { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-KasFE.framer-swrw9a { gap: 0px; } .framer-KasFE.framer-swrw9a > * { margin: 0px; margin-left: calc(6px / 2); margin-right: calc(6px / 2); } .framer-KasFE.framer-swrw9a > :first-child { margin-left: 0px; } .framer-KasFE.framer-swrw9a > :last-child { margin-right: 0px; } }",
	...css,
	'.framer-KasFE[data-border="true"]::after, .framer-KasFE [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerfAGKBobJE = withCSS(Component, css2, "framer-KasFE");
var stdin_default = FramerfAGKBobJE;
FramerfAGKBobJE.displayName = "Buttons [Ghost]";
FramerfAGKBobJE.defaultProps = {
	height: 48,
	width: 188.5,
};
addPropertyControls(FramerfAGKBobJE, {
	H7SbZkGtw: {
		__defaultAssetReference:
			"data:framer/asset-reference,R7H2r6TtI15RajTvXbuZc99aLIc.svg?originalFilename=Arrow-Right-black.svg&preferredSize=auto",
		title: "Image-Left",
		type: ControlType.ResponsiveImage,
	},
	bCHVikJAV: {
		__defaultAssetReference:
			"data:framer/asset-reference,m34iBIKYEYLNuIWIy8F8pi0uo.svg?originalFilename=Arrow-Right.svg&preferredSize=auto",
		title: "Image-Right",
		type: ControlType.ResponsiveImage,
	},
	iK9Mx1VvZ: {
		defaultValue: true,
		title: "Icon-Right",
		type: ControlType.Boolean,
	},
	aXo20rNiT: {
		defaultValue: true,
		title: "Icon-Left",
		type: ControlType.Boolean,
	},
	sFDdZDiqV: {
		defaultValue: "Back to Case Studies",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(
	FramerfAGKBobJE,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:buttons-ghost
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonsGhostFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var buttons_ghost_default = ComponentWithRoot;
export { buttons_ghost_default as default };
