// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5393b9314a548245 "Osaka Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * label?: string // Label
 * rightIcon?: {src: string, srcSet?: string, alt?: string} // Right Icon
 * leftIcon?: {src: string, srcSet?: string, alt?: string} // Left Icon
 * showRightIcon?: boolean // Show Right Icon
 * showLeftIcon?: boolean // Show Left Icon
 * link?: string // Link
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-3CAFTFQD.js";
import { routes } from "./chunks/chunk-RIZBGR4E.js";

// virtual:buttons-primary
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/iJGcyhgQLVEqFJBeo33g/FsM635DAmHAfFpot3Dmb/bF7QUg9gI.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Image,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	B7hkadEAL: {
		hover: true,
		pressed: true,
	},
};
var cycleOrder = ["B7hkadEAL"];
var serializationHash = "framer-q4DCa";
var variantClassNames = {
	B7hkadEAL: "framer-v-uhbl0n",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var getProps = ({
	height,
	id,
	label,
	leftIcon,
	link,
	rightIcon,
	showLeftIcon,
	showRightIcon,
	width,
	...props
}) => {
	var _ref, _ref1, _ref2, _ref3, _ref4;
	return {
		...props,
		EtmZfwjtW:
			(_ref =
				leftIcon !== null && leftIcon !== void 0
					? leftIcon
					: props.EtmZfwjtW) !== null && _ref !== void 0
				? _ref
				: {
						src: "https://framerusercontent.com/images/0kPPCMqeqs0Vdm29LHJzLuihq0.svg",
					},
		eUVN_B4b9:
			(_ref1 =
				showLeftIcon !== null && showLeftIcon !== void 0
					? showLeftIcon
					: props.eUVN_B4b9) !== null && _ref1 !== void 0
				? _ref1
				: true,
		h04wKS05X:
			(_ref2 = label !== null && label !== void 0 ? label : props.h04wKS05X) !==
				null && _ref2 !== void 0
				? _ref2
				: "Buy Template",
		qFvMY2XBe:
			(_ref3 =
				rightIcon !== null && rightIcon !== void 0
					? rightIcon
					: props.qFvMY2XBe) !== null && _ref3 !== void 0
				? _ref3
				: {
						src: "https://framerusercontent.com/images/i4lIrW48BI3ShNtliWbKx0GB7A.svg",
					},
		TA373f1GM: link !== null && link !== void 0 ? link : props.TA373f1GM,
		ya5sPXSOD:
			(_ref4 =
				showRightIcon !== null && showRightIcon !== void 0
					? showRightIcon
					: props.ya5sPXSOD) !== null && _ref4 !== void 0
				? _ref4
				: true,
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		h04wKS05X,
		qFvMY2XBe,
		EtmZfwjtW,
		ya5sPXSOD,
		eUVN_B4b9,
		TA373f1GM,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "B7hkadEAL",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link href={TA373f1GM} openInNewTab={false}>
						<motion.a
							{...restProps}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-uhbl0n", className2, classNames)} framer-ekydtb`}
							data-framer-name={"Primary Button"}
							layoutDependency={layoutDependency}
							layoutId={"B7hkadEAL"}
							onHoverEnd={() =>
								setGestureState({
									isHovered: false,
								})
							}
							onHoverStart={() =>
								setGestureState({
									isHovered: true,
								})
							}
							onTap={() =>
								setGestureState({
									isPressed: false,
								})
							}
							onTapCancel={() =>
								setGestureState({
									isPressed: false,
								})
							}
							onTapStart={() =>
								setGestureState({
									isPressed: true,
								})
							}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								backgroundColor: "rgb(52, 65, 74)",
								borderBottomLeftRadius: 40,
								borderBottomRightRadius: 40,
								borderTopLeftRadius: 40,
								borderTopRightRadius: 40,
								...style,
							}}
							variants={{
								"B7hkadEAL-hover": {
									backgroundColor: "rgb(34, 42, 48)",
								},
								"B7hkadEAL-pressed": {
									backgroundColor: "rgb(0, 0, 0)",
								},
							}}
							{...addPropertyOverrides(
								{
									"B7hkadEAL-hover": {
										"data-framer-name": void 0,
									},
									"B7hkadEAL-pressed": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							{eUVN_B4b9 && (
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 24,
										intrinsicWidth: 24,
										pixelHeight: 24,
										pixelWidth: 24,
										sizes: "24px",
										...toResponsiveImage(EtmZfwjtW),
									}}
									className={"framer-113reuf"}
									data-framer-name={"Arrow-Right"}
									layoutDependency={layoutDependency}
									layoutId={"DCtvVxe0W"}
								/>
							)}
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1cxbodr"}
								data-framer-name={"Buy Template"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"CuecfckRU"}
								style={{
									"--extracted-a0htzi":
										"var(--token-f96ba792-740e-4a6c-9838-946a3dd381d3, rgb(255, 255, 255))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={h04wKS05X}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-1v1rg9h"}
										data-styles-preset={"I04wxwwIQ"}
										style={{
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-f96ba792-740e-4a6c-9838-946a3dd381d3, rgb(255, 255, 255)))",
										}}
									>
										{"Buy Template"}
									</motion.h3>
								</React.Fragment>
							</RichText>
							{ya5sPXSOD && (
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 24,
										intrinsicWidth: 24,
										pixelHeight: 24,
										pixelWidth: 24,
										sizes: "24px",
										...toResponsiveImage(qFvMY2XBe),
									}}
									className={"framer-ev1lzq"}
									data-framer-name={"Arrow-Right"}
									layoutDependency={layoutDependency}
									layoutId={"rGPjz6R5v"}
								/>
							)}
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-q4DCa.framer-ekydtb, .framer-q4DCa .framer-ekydtb { display: block; }",
	".framer-q4DCa.framer-uhbl0n { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: 48px; justify-content: center; overflow: hidden; padding: 13px 20px 13px 20px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-q4DCa .framer-113reuf, .framer-q4DCa .framer-ev1lzq { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 24px); overflow: hidden; position: relative; width: 24px; }",
	".framer-q4DCa .framer-1cxbodr { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-q4DCa.framer-uhbl0n { gap: 0px; } .framer-q4DCa.framer-uhbl0n > * { margin: 0px; margin-left: calc(6px / 2); margin-right: calc(6px / 2); } .framer-q4DCa.framer-uhbl0n > :first-child { margin-left: 0px; } .framer-q4DCa.framer-uhbl0n > :last-child { margin-right: 0px; } }",
	".framer-q4DCa.framer-v-uhbl0n.hover.framer-uhbl0n, .framer-q4DCa.framer-v-uhbl0n.pressed.framer-uhbl0n { gap: 12px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-q4DCa.framer-v-uhbl0n.hover.framer-uhbl0n { gap: 0px; } .framer-q4DCa.framer-v-uhbl0n.hover.framer-uhbl0n > * { margin: 0px; margin-left: calc(12px / 2); margin-right: calc(12px / 2); } .framer-q4DCa.framer-v-uhbl0n.hover.framer-uhbl0n > :first-child { margin-left: 0px; } .framer-q4DCa.framer-v-uhbl0n.hover.framer-uhbl0n > :last-child { margin-right: 0px; } }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-q4DCa.framer-v-uhbl0n.pressed.framer-uhbl0n { gap: 0px; } .framer-q4DCa.framer-v-uhbl0n.pressed.framer-uhbl0n > * { margin: 0px; margin-left: calc(12px / 2); margin-right: calc(12px / 2); } .framer-q4DCa.framer-v-uhbl0n.pressed.framer-uhbl0n > :first-child { margin-left: 0px; } .framer-q4DCa.framer-v-uhbl0n.pressed.framer-uhbl0n > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerbF7QUg9gI = withCSS(Component, css2, "framer-q4DCa");
var stdin_default = FramerbF7QUg9gI;
FramerbF7QUg9gI.displayName = "Buttons [Primary]";
FramerbF7QUg9gI.defaultProps = {
	height: 48,
	width: 183.5,
};
addPropertyControls(FramerbF7QUg9gI, {
	h04wKS05X: {
		defaultValue: "Buy Template",
		displayTextArea: false,
		title: "Label",
		type: ControlType.String,
	},
	qFvMY2XBe: {
		__defaultAssetReference:
			"data:framer/asset-reference,i4lIrW48BI3ShNtliWbKx0GB7A.svg?originalFilename=white.svg&preferredSize=auto",
		title: "Right Icon",
		type: ControlType.ResponsiveImage,
	},
	EtmZfwjtW: {
		__defaultAssetReference:
			"data:framer/asset-reference,0kPPCMqeqs0Vdm29LHJzLuihq0.svg?originalFilename=arrow-left-white.svg&preferredSize=auto",
		title: "Left Icon",
		type: ControlType.ResponsiveImage,
	},
	ya5sPXSOD: {
		defaultValue: true,
		title: "Show Right Icon",
		type: ControlType.Boolean,
	},
	eUVN_B4b9: {
		defaultValue: true,
		title: "Show Left Icon",
		type: ControlType.Boolean,
	},
	TA373f1GM: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FramerbF7QUg9gI,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:buttons-primary
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonsPrimaryFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var buttons_primary_default = ComponentWithRoot;
export { buttons_primary_default as default };
