// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5393b9314a548245 "Osaka Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Variant 3' | 'Variant 4' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-RIZBGR4E.js";

// virtual:images-hero-section
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/pDgHoXzttkHGX1Qx3jMU/QUtu6XAvSXwXc7GN3mNH/bcHYVJaRD.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["r_2FmPuT9", "aHkkGyPR5", "Go852kg7G", "cf8vKYDvt"];
var serializationHash = "framer-dqsZ2";
var variantClassNames = {
	aHkkGyPR5: "framer-v-1oeiwy0",
	cf8vKYDvt: "framer-v-1pod4uw",
	Go852kg7G: "framer-v-u6qc68",
	r_2FmPuT9: "framer-v-drzu6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "r_2FmPuT9",
	"Variant 2": "aHkkGyPR5",
	"Variant 3": "Go852kg7G",
	"Variant 4": "cf8vKYDvt",
};
var getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "r_2FmPuT9",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "r_2FmPuT9",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Image
						{...restProps}
						background={{
							alt: "",
							fit: "fill",
							intrinsicHeight: 588,
							intrinsicWidth: 1011,
							pixelHeight: 588,
							pixelWidth: 1011,
							sizes:
								(componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.width) || "100vw",
							src: "https://framerusercontent.com/images/8pRPLkCsb5qgF3COxBPDEVU.png",
							srcSet:
								"https://framerusercontent.com/images/8pRPLkCsb5qgF3COxBPDEVU.png?scale-down-to=512 512w,https://framerusercontent.com/images/8pRPLkCsb5qgF3COxBPDEVU.png 1011w",
						}}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-drzu6",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"r_2FmPuT9"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								aHkkGyPR5: {
									"data-framer-name": "Variant 2",
									background: {
										alt: "",
										fit: "fill",
										intrinsicHeight: 196,
										intrinsicWidth: 337,
										pixelHeight: 196,
										pixelWidth: 337,
										src: "https://framerusercontent.com/images/BEsphkhacjRyWAgsXD6nhNWfNY.svg",
									},
								},
								cf8vKYDvt: {
									"data-framer-name": "Variant 4",
									background: {
										alt: "",
										fit: "fill",
										intrinsicHeight: 588,
										intrinsicWidth: 1011,
										pixelHeight: 588,
										pixelWidth: 1011,
										sizes:
											(componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.width) || "100vw",
										src: "https://framerusercontent.com/images/X4yhAzSYSsbBKxq0lvkdGkgvU8.png",
										srcSet:
											"https://framerusercontent.com/images/X4yhAzSYSsbBKxq0lvkdGkgvU8.png?scale-down-to=512 512w,https://framerusercontent.com/images/X4yhAzSYSsbBKxq0lvkdGkgvU8.png 1011w",
									},
								},
								Go852kg7G: {
									"data-framer-name": "Variant 3",
									background: {
										alt: "",
										fit: "fill",
										intrinsicHeight: 196,
										intrinsicWidth: 337,
										pixelHeight: 196,
										pixelWidth: 337,
										src: "https://framerusercontent.com/images/cpxLVaJHN2D2tu5xOpsHmLW2pE.svg",
									},
								},
							},
							baseVariant,
							gestureVariant,
						)}
					/>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-dqsZ2.framer-4onrbq, .framer-dqsZ2 .framer-4onrbq { display: block; }",
	".framer-dqsZ2.framer-drzu6 { height: 220px; overflow: hidden; position: relative; width: 378px; }",
];
var FramerbcHYVJaRD = withCSS(Component, css, "framer-dqsZ2");
var stdin_default = FramerbcHYVJaRD;
FramerbcHYVJaRD.displayName = "Images [Hero Section]";
FramerbcHYVJaRD.defaultProps = {
	height: 220,
	width: 378,
};
addPropertyControls(FramerbcHYVJaRD, {
	variant: {
		options: ["r_2FmPuT9", "aHkkGyPR5", "Go852kg7G", "cf8vKYDvt"],
		optionTitles: ["Variant 1", "Variant 2", "Variant 3", "Variant 4"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerbcHYVJaRD,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:images-hero-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ImagesHeroSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var images_hero_section_default = ComponentWithRoot;
export { images_hero_section_default as default };
