// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5393b9314a548245 "Osaka Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * image2?: {src: string, srcSet?: string, alt?: string} // Image 2
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-4BZMBQI4.js";
import { routes } from "./chunks/chunk-RIZBGR4E.js";

// virtual:made-by-love-footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ks4xlCRYQy2cH2FhaZzl/LZ8XTA8uZNrgTWpJhuHk/wzL3oQiBl.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Image,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	LP00zET_P: {
		hover: true,
	},
};
var cycleOrder = ["LP00zET_P"];
var serializationHash = "framer-6z9P5";
var variantClassNames = {
	LP00zET_P: "framer-v-1bzu1yw",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var getProps = ({ height, id, image, image2, width, ...props }) => {
	var _ref, _ref1;
	return {
		...props,
		vWd6i88B3:
			(_ref =
				image2 !== null && image2 !== void 0 ? image2 : props.vWd6i88B3) !==
				null && _ref !== void 0
				? _ref
				: {
						src: "https://framerusercontent.com/images/VXFgVIYgW2dpy2w3CUcYnuGZ7I.svg",
					},
		yfDsaoif_:
			(_ref1 = image !== null && image !== void 0 ? image : props.yfDsaoif_) !==
				null && _ref1 !== void 0
				? _ref1
				: {
						src: "https://framerusercontent.com/images/zwVTyAsxv3pkWdaNuqPAxZXqI.svg",
					},
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		yfDsaoif_,
		vWd6i88B3,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "LP00zET_P",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (gestureVariant === "LP00zET_P-hover") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (gestureVariant === "LP00zET_P-hover") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1bzu1yw",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"LP00zET_P"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							borderBottomLeftRadius: 40,
							borderBottomRightRadius: 40,
							borderTopLeftRadius: 40,
							borderTopRightRadius: 40,
							...style,
						}}
						{...addPropertyOverrides(
							{
								"LP00zET_P-hover": {
									"data-framer-name": void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() && (
							<Image
								background={{
									alt: "",
									fit: "fill",
									sizes: "32px",
									...toResponsiveImage(yfDsaoif_),
								}}
								className={"framer-olr5oy"}
								data-framer-name={"Heart"}
								layoutDependency={layoutDependency}
								layoutId={"O5Yx2jijb"}
							>
								<SVG
									className={"framer-kvhceb"}
									data-framer-name={'\u{1F986} icon "heart"'}
									fill={"rgba(0,0,0,1)"}
									intrinsicHeight={20}
									intrinsicWidth={22}
									layoutDependency={layoutDependency}
									layoutId={"I186:20998;178:769"}
									svg={
										'<svg width="22" height="20" viewBox="0 0 22 20" fill="none" xmlns="http://www.w3.org/2000/svg">\n<path d="M7.97106 0.666626H4.23773V2.53329H2.37106V4.39996H0.504395V9.99996H2.37106V11.8666H4.23773V13.7333H6.10439V15.6H7.97106V17.4666H9.83773V19.3333H11.7044V17.4666H13.5711V15.6H15.4377V13.7333H17.3044V11.8666H19.1711V9.99996H21.0377V4.39996H19.1711V2.53329H17.3044V0.666626H13.5711V2.53329H11.7044V4.39996H9.83773V2.53329H7.97106V0.666626ZM7.97106 2.53329V4.39996H9.83773V6.26663H11.7044V4.39996H13.5711V2.53329H17.3044V4.39996H19.1711V9.99996H17.3044V11.8666H15.4377V13.7333H13.5711V15.6H11.7044V17.4666H9.83773V15.6H7.97106V13.7333H6.10439V11.8666H4.23773V9.99996H2.37106V4.39996H4.23773V2.53329H7.97106Z" fill="white"/>\n</svg>\n'
									}
									withExternalLayout={true}
								/>
							</Image>
						)}
						{isDisplayed1() && (
							<Image
								background={{
									alt: "",
									fit: "fill",
									...toResponsiveImage(vWd6i88B3),
								}}
								className={"framer-6r7to1"}
								data-framer-name={"Heart"}
								layoutDependency={layoutDependency}
								layoutId={"HqL7F7ZGq"}
								{...addPropertyOverrides(
									{
										"LP00zET_P-hover": {
											background: {
												alt: "",
												fit: "fill",
												sizes: "32px",
												...toResponsiveImage(vWd6i88B3),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
						<RichText
							__fromCanvasComponent={true}
							className={"framer-156q34g"}
							data-framer-name={"made by love."}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"ne2zSzgg9"}
							style={{
								"--extracted-gdpscs":
									"var(--token-f96ba792-740e-4a6c-9838-946a3dd381d3, rgb(255, 255, 255))",
								"--framer-paragraph-spacing": "0px",
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.h1
									className={"framer-styles-preset-x6zg8p"}
									data-styles-preset={"grlDjfGrE"}
									style={{
										"--framer-text-color":
											"var(--extracted-gdpscs, var(--token-f96ba792-740e-4a6c-9838-946a3dd381d3, rgb(255, 255, 255)))",
									}}
								>
									{"made by love."}
								</motion.h1>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-6z9P5.framer-1vq29on, .framer-6z9P5 .framer-1vq29on { display: block; }",
	".framer-6z9P5.framer-1bzu1yw { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-6z9P5 .framer-olr5oy, .framer-6z9P5 .framer-6r7to1 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 32px); overflow: hidden; position: relative; width: 32px; }",
	".framer-6z9P5 .framer-kvhceb { flex: none; height: 20px; left: 5px; position: absolute; top: 6px; width: 22px; }",
	".framer-6z9P5 .framer-156q34g { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-6z9P5.framer-1bzu1yw { gap: 0px; } .framer-6z9P5.framer-1bzu1yw > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-6z9P5.framer-1bzu1yw > :first-child { margin-left: 0px; } .framer-6z9P5.framer-1bzu1yw > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerwzL3oQiBl = withCSS(Component, css2, "framer-6z9P5");
var stdin_default = FramerwzL3oQiBl;
FramerwzL3oQiBl.displayName = "Made By Love [Footer]";
FramerwzL3oQiBl.defaultProps = {
	height: 32,
	width: 144.5,
};
addPropertyControls(FramerwzL3oQiBl, {
	yfDsaoif_: {
		__defaultAssetReference:
			"data:framer/asset-reference,zwVTyAsxv3pkWdaNuqPAxZXqI.svg?originalFilename=Heart.svg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	vWd6i88B3: {
		__defaultAssetReference:
			"data:framer/asset-reference,VXFgVIYgW2dpy2w3CUcYnuGZ7I.svg?originalFilename=Heart.svg&preferredSize=auto",
		title: "Image 2",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerwzL3oQiBl,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:made-by-love-footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MadeByLoveFooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var made_by_love_footer_default = ComponentWithRoot;
export { made_by_love_footer_default as default };
