// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 5393b9314a548245 "Osaka Template (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop 1' | 'Desktop 2' | 'Desktop 3' | 'Desktop 4' | 'Desktop 5' | 'Tablet' | 'Tablet 2' | 'Tablet 3' | 'Tablet 4' | 'Tablet 5' | 'Mobile 1' | 'Mobile 2' | 'Mobile 3' | 'Mobile 4' | 'Mobile 5' // Variant
 * title1?: string // Title 1
 * title2?: string // Title2
 * title3?: string // Title 3
 * title4?: string // Title 4
 * color2?: string // Color 2
}} Props

 */
import {
	className,
	className2,
	className3,
	css,
	css2,
	css3,
	fonts,
	fonts2,
	fonts3,
} from "./chunks/chunk-BN43Q72B.js";
import { routes } from "./chunks/chunk-RIZBGR4E.js";

// virtual:text-animation-hero-section
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vsytG9kU7Ju6ncb4docj/G4gjvjnWuOXt6zW6Twlk/dowJGOcnx.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = [
	"Y3Wng9ic3",
	"NvQlB76ip",
	"WJCNW1X6P",
	"BydgrkuMq",
	"WehEgKult",
	"uIE50kYTK",
	"KsbdY7ojc",
	"rclV5YU1T",
	"En65AYq8W",
	"i5eDoNflh",
	"OGKVC19Xt",
	"fvHknp2PU",
	"Hn0EEn9cO",
	"oQvYtI6U2",
	"YaGqp8wc_",
];
var serializationHash = "framer-kYndM";
var variantClassNames = {
	BydgrkuMq: "framer-v-1vdosr9",
	En65AYq8W: "framer-v-86z536",
	fvHknp2PU: "framer-v-x5j6he",
	Hn0EEn9cO: "framer-v-z1h531",
	i5eDoNflh: "framer-v-kjbmn5",
	KsbdY7ojc: "framer-v-1dczw7q",
	NvQlB76ip: "framer-v-15qdun0",
	OGKVC19Xt: "framer-v-1t062nr",
	oQvYtI6U2: "framer-v-yll8be",
	rclV5YU1T: "framer-v-1lwv4yd",
	uIE50kYTK: "framer-v-lz4yr2",
	WehEgKult: "framer-v-18cyl7s",
	WJCNW1X6P: "framer-v-dnoi0v",
	Y3Wng9ic3: "framer-v-12elvc5",
	YaGqp8wc_: "framer-v-y9w877",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	duration: 0,
	type: "tween",
};
var transition2 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	"Desktop 1": "Y3Wng9ic3",
	"Desktop 2": "NvQlB76ip",
	"Desktop 3": "WJCNW1X6P",
	"Desktop 4": "BydgrkuMq",
	"Desktop 5": "WehEgKult",
	"Mobile 1": "OGKVC19Xt",
	"Mobile 2": "fvHknp2PU",
	"Mobile 3": "Hn0EEn9cO",
	"Mobile 4": "oQvYtI6U2",
	"Mobile 5": "YaGqp8wc_",
	"Tablet 2": "KsbdY7ojc",
	"Tablet 3": "rclV5YU1T",
	"Tablet 4": "En65AYq8W",
	"Tablet 5": "i5eDoNflh",
	Tablet: "uIE50kYTK",
};
var getProps = ({
	color2,
	height,
	id,
	title1,
	title2,
	title3,
	title4,
	width,
	...props
}) => {
	var _ref,
		_ref1,
		_ref2,
		_ref3,
		_ref4,
		_humanReadableVariantMap_props_variant,
		_ref5;
	return {
		...props,
		AKBUKrFCf:
			(_ref =
				title1 !== null && title1 !== void 0 ? title1 : props.AKBUKrFCf) !==
				null && _ref !== void 0
				? _ref
				: "digital product.",
		KzPuVZC7w:
			(_ref1 =
				title4 !== null && title4 !== void 0 ? title4 : props.KzPuVZC7w) !==
				null && _ref1 !== void 0
				? _ref1
				: "mobile application.",
		M3xrlQMNd:
			(_ref2 =
				color2 !== null && color2 !== void 0 ? color2 : props.M3xrlQMNd) !==
				null && _ref2 !== void 0
				? _ref2
				: "var(--token-537bfcfa-1832-4a09-9413-729564804849, rgb(52, 65, 74))",
		pORcANL6Z:
			(_ref3 =
				title2 !== null && title2 !== void 0 ? title2 : props.pORcANL6Z) !==
				null && _ref3 !== void 0
				? _ref3
				: "landing pages.",
		UlOOaXh04:
			(_ref4 =
				title3 !== null && title3 !== void 0 ? title3 : props.UlOOaXh04) !==
				null && _ref4 !== void 0
				? _ref4
				: "visual identity.",
		variant:
			(_ref5 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref5 !== void 0
				? _ref5
				: "Y3Wng9ic3",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		AKBUKrFCf,
		pORcANL6Z,
		UlOOaXh04,
		KzPuVZC7w,
		M3xrlQMNd,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Y3Wng9ic3",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear1j2t158 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("NvQlB76ip"), 1e3);
	});
	const onAppear1xj4mkw = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("WJCNW1X6P"), 2e3);
	});
	const onAppear1szq092 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("BydgrkuMq"), 2e3);
	});
	const onAppearpe9e88 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("WehEgKult"), 2e3);
	});
	const onAppear6whto0 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("Y3Wng9ic3"), 1e3);
	});
	const onAppearqllaux = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("KsbdY7ojc"), 1e3);
	});
	const onTapStarty1g29m = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: true,
		});
		await delay(() => setVariant("rclV5YU1T"), 2e3);
	});
	const onAppearx9jjpq = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("En65AYq8W"), 2e3);
	});
	const onAppear4exy7t = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("i5eDoNflh"), 2e3);
	});
	const onAppearh7gb8k = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("uIE50kYTK"), 1e3);
	});
	const onAppearyisp2z = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("fvHknp2PU"), 1e3);
	});
	const onAppear16bc7y2 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("Hn0EEn9cO"), 2e3);
	});
	const onAppearnd0fw5 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("oQvYtI6U2"), 2e3);
	});
	const onAppear1xq3z8n = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("YaGqp8wc_"), 2e3);
	});
	const onAppear1m2vnav = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("OGKVC19Xt"), 1e3);
	});
	useOnVariantChange(baseVariant, {
		BydgrkuMq: onAppearpe9e88,
		default: onAppear1j2t158,
		En65AYq8W: onAppear4exy7t,
		fvHknp2PU: onAppear16bc7y2,
		Hn0EEn9cO: onAppearnd0fw5,
		i5eDoNflh: onAppearh7gb8k,
		KsbdY7ojc: void 0,
		NvQlB76ip: onAppear1xj4mkw,
		OGKVC19Xt: onAppearyisp2z,
		oQvYtI6U2: onAppear1xq3z8n,
		rclV5YU1T: onAppearx9jjpq,
		uIE50kYTK: onAppearqllaux,
		WehEgKult: onAppear6whto0,
		WJCNW1X6P: onAppear1szq092,
		YaGqp8wc_: onAppear1m2vnav,
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className3, className, className2];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							BydgrkuMq: {
								value: transition2,
							},
							fvHknp2PU: {
								value: transition2,
							},
							Hn0EEn9cO: {
								value: transition2,
							},
							i5eDoNflh: {
								value: transition2,
							},
							NvQlB76ip: {
								value: transition2,
							},
							oQvYtI6U2: {
								value: transition2,
							},
							WehEgKult: {
								value: transition2,
							},
							WJCNW1X6P: {
								value: transition2,
							},
							YaGqp8wc_: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-12elvc5",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"Y3Wng9ic3"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								BydgrkuMq: {
									"data-framer-name": "Desktop 4",
								},
								En65AYq8W: {
									"data-framer-name": "Tablet 4",
								},
								fvHknp2PU: {
									"data-framer-name": "Mobile 2",
								},
								Hn0EEn9cO: {
									"data-framer-name": "Mobile 3",
								},
								i5eDoNflh: {
									"data-framer-name": "Tablet 5",
								},
								KsbdY7ojc: {
									"data-framer-name": "Tablet 2",
									onTapStart: onTapStarty1g29m,
								},
								NvQlB76ip: {
									"data-framer-name": "Desktop 2",
								},
								OGKVC19Xt: {
									"data-framer-name": "Mobile 1",
								},
								oQvYtI6U2: {
									"data-framer-name": "Mobile 4",
								},
								rclV5YU1T: {
									"data-framer-name": "Tablet 3",
								},
								uIE50kYTK: {
									"data-framer-name": "Tablet",
								},
								WehEgKult: {
									"data-framer-name": "Desktop 5",
								},
								WJCNW1X6P: {
									"data-framer-name": "Desktop 3",
								},
								YaGqp8wc_: {
									"data-framer-name": "Mobile 5",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-yiut5d"}
							layoutDependency={layoutDependency}
							layoutId={"FcJvrmBHH"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-18emmmu"}
								data-framer-name={"digital product. (2)"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"UpdIVtXKV"}
								style={{
									"--extracted-gdpscs":
										"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									"--framer-paragraph-spacing": "0px",
									"--variable-reference-M3xrlQMNd-dowJGOcnx": M3xrlQMNd,
								}}
								text={AKBUKrFCf}
								variants={{
									En65AYq8W: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									fvHknp2PU: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									Hn0EEn9cO: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									i5eDoNflh: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									KsbdY7ojc: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									OGKVC19Xt: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									oQvYtI6U2: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									rclV5YU1T: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									uIE50kYTK: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									YaGqp8wc_: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										En65AYq8W: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h2>
												</React.Fragment>
											),
											transformTemplate: transformTemplate1,
										},
										fvHknp2PU: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h3>
												</React.Fragment>
											),
											transformTemplate: transformTemplate1,
										},
										Hn0EEn9cO: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h3>
												</React.Fragment>
											),
											transformTemplate: transformTemplate1,
										},
										i5eDoNflh: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h2>
												</React.Fragment>
											),
											transformTemplate: transformTemplate1,
										},
										KsbdY7ojc: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h2>
												</React.Fragment>
											),
											transformTemplate: transformTemplate1,
										},
										OGKVC19Xt: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h3>
												</React.Fragment>
											),
											transformTemplate: transformTemplate1,
										},
										oQvYtI6U2: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h3>
												</React.Fragment>
											),
											transformTemplate: transformTemplate1,
										},
										rclV5YU1T: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h2>
												</React.Fragment>
											),
											transformTemplate: transformTemplate1,
										},
										uIE50kYTK: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h2>
												</React.Fragment>
											),
											transformTemplate: transformTemplate1,
										},
										WehEgKult: {
											transformTemplate: transformTemplate1,
										},
										YaGqp8wc_: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h3>
												</React.Fragment>
											),
											transformTemplate: transformTemplate1,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h1
										className={"framer-styles-preset-fqiunk"}
										data-styles-preset={"RWGve82MW"}
										style={{
											"--framer-text-color":
												"var(--extracted-gdpscs, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
										}}
									>
										{"digital product."}
									</motion.h1>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-f1jmb3"}
								data-framer-name={"landing pages."}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"REp3fiAe8"}
								style={{
									"--extracted-gdpscs":
										"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									"--framer-paragraph-spacing": "0px",
									"--variable-reference-M3xrlQMNd-dowJGOcnx": M3xrlQMNd,
								}}
								text={pORcANL6Z}
								variants={{
									En65AYq8W: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									fvHknp2PU: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									Hn0EEn9cO: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									i5eDoNflh: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									KsbdY7ojc: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									OGKVC19Xt: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									oQvYtI6U2: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									rclV5YU1T: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									uIE50kYTK: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									YaGqp8wc_: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										BydgrkuMq: {
											transformTemplate: transformTemplate1,
										},
										En65AYq8W: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"landing pages."}
													</motion.h2>
												</React.Fragment>
											),
											transformTemplate: transformTemplate1,
										},
										fvHknp2PU: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"landing pages."}
													</motion.h3>
												</React.Fragment>
											),
										},
										Hn0EEn9cO: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"landing pages."}
													</motion.h3>
												</React.Fragment>
											),
										},
										i5eDoNflh: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"landing pages."}
													</motion.h2>
												</React.Fragment>
											),
										},
										KsbdY7ojc: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"landing pages."}
													</motion.h2>
												</React.Fragment>
											),
										},
										OGKVC19Xt: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"landing pages."}
													</motion.h3>
												</React.Fragment>
											),
										},
										oQvYtI6U2: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"landing pages."}
													</motion.h3>
												</React.Fragment>
											),
											transformTemplate: transformTemplate1,
										},
										rclV5YU1T: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"landing pages."}
													</motion.h2>
												</React.Fragment>
											),
										},
										uIE50kYTK: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"landing pages."}
													</motion.h2>
												</React.Fragment>
											),
										},
										YaGqp8wc_: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"landing pages."}
													</motion.h3>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h1
										className={"framer-styles-preset-fqiunk"}
										data-styles-preset={"RWGve82MW"}
										style={{
											"--framer-text-color":
												"var(--extracted-gdpscs, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
										}}
									>
										{"landing pages."}
									</motion.h1>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-16027zo"}
								data-framer-name={"digital product."}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"cBgy6Jzi_"}
								style={{
									"--extracted-gdpscs":
										"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									"--framer-paragraph-spacing": "0px",
									"--variable-reference-M3xrlQMNd-dowJGOcnx": M3xrlQMNd,
								}}
								text={AKBUKrFCf}
								variants={{
									En65AYq8W: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									fvHknp2PU: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									Hn0EEn9cO: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									i5eDoNflh: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									KsbdY7ojc: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									OGKVC19Xt: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									oQvYtI6U2: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									rclV5YU1T: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									uIE50kYTK: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									YaGqp8wc_: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										En65AYq8W: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h2>
												</React.Fragment>
											),
										},
										fvHknp2PU: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h3>
												</React.Fragment>
											),
										},
										Hn0EEn9cO: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h3>
												</React.Fragment>
											),
										},
										i5eDoNflh: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h2>
												</React.Fragment>
											),
										},
										KsbdY7ojc: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h2>
												</React.Fragment>
											),
										},
										OGKVC19Xt: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h3>
												</React.Fragment>
											),
										},
										oQvYtI6U2: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h3>
												</React.Fragment>
											),
										},
										rclV5YU1T: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h2>
												</React.Fragment>
											),
										},
										uIE50kYTK: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h2>
												</React.Fragment>
											),
										},
										YaGqp8wc_: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"digital product."}
													</motion.h3>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h1
										className={"framer-styles-preset-fqiunk"}
										data-styles-preset={"RWGve82MW"}
										style={{
											"--framer-text-color":
												"var(--extracted-gdpscs, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
										}}
									>
										{"digital product."}
									</motion.h1>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1314qhq"}
								data-framer-name={"visual identity."}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"TiedQQEgn"}
								style={{
									"--extracted-gdpscs":
										"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									"--framer-paragraph-spacing": "0px",
									"--variable-reference-M3xrlQMNd-dowJGOcnx": M3xrlQMNd,
								}}
								text={UlOOaXh04}
								transformTemplate={transformTemplate1}
								variants={{
									En65AYq8W: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									fvHknp2PU: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									Hn0EEn9cO: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									i5eDoNflh: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									KsbdY7ojc: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									OGKVC19Xt: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									oQvYtI6U2: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									rclV5YU1T: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									uIE50kYTK: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									YaGqp8wc_: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										En65AYq8W: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"visual identity."}
													</motion.h2>
												</React.Fragment>
											),
										},
										fvHknp2PU: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"visual identity."}
													</motion.h3>
												</React.Fragment>
											),
										},
										Hn0EEn9cO: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"visual identity."}
													</motion.h3>
												</React.Fragment>
											),
										},
										i5eDoNflh: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"visual identity."}
													</motion.h2>
												</React.Fragment>
											),
										},
										KsbdY7ojc: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"visual identity."}
													</motion.h2>
												</React.Fragment>
											),
										},
										OGKVC19Xt: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"visual identity."}
													</motion.h3>
												</React.Fragment>
											),
										},
										oQvYtI6U2: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"visual identity."}
													</motion.h3>
												</React.Fragment>
											),
										},
										rclV5YU1T: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"visual identity."}
													</motion.h2>
												</React.Fragment>
											),
										},
										uIE50kYTK: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"visual identity."}
													</motion.h2>
												</React.Fragment>
											),
										},
										YaGqp8wc_: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"visual identity."}
													</motion.h3>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h1
										className={"framer-styles-preset-fqiunk"}
										data-styles-preset={"RWGve82MW"}
										style={{
											"--framer-text-color":
												"var(--extracted-gdpscs, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
										}}
									>
										{"visual identity."}
									</motion.h1>
								</React.Fragment>
							</RichText>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1p9bmdu"}
								data-framer-name={"mobile application."}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"BO8wt4Mnh"}
								style={{
									"--extracted-gdpscs":
										"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									"--framer-paragraph-spacing": "0px",
									"--variable-reference-M3xrlQMNd-dowJGOcnx": M3xrlQMNd,
								}}
								text={KzPuVZC7w}
								variants={{
									En65AYq8W: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									fvHknp2PU: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									Hn0EEn9cO: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									i5eDoNflh: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									KsbdY7ojc: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									OGKVC19Xt: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									oQvYtI6U2: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									rclV5YU1T: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									uIE50kYTK: {
										"--extracted-1of0zx5":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
									YaGqp8wc_: {
										"--extracted-a0htzi":
											"var(--variable-reference-M3xrlQMNd-dowJGOcnx)",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										En65AYq8W: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"mobile application."}
													</motion.h2>
												</React.Fragment>
											),
										},
										fvHknp2PU: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"mobile application."}
													</motion.h3>
												</React.Fragment>
											),
										},
										Hn0EEn9cO: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"mobile application."}
													</motion.h3>
												</React.Fragment>
											),
										},
										i5eDoNflh: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"mobile application."}
													</motion.h2>
												</React.Fragment>
											),
										},
										KsbdY7ojc: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"mobile application."}
													</motion.h2>
												</React.Fragment>
											),
										},
										NvQlB76ip: {
											transformTemplate: transformTemplate1,
										},
										OGKVC19Xt: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"mobile application."}
													</motion.h3>
												</React.Fragment>
											),
										},
										oQvYtI6U2: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"mobile application."}
													</motion.h3>
												</React.Fragment>
											),
										},
										rclV5YU1T: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"mobile application."}
													</motion.h2>
												</React.Fragment>
											),
										},
										uIE50kYTK: {
											children: (
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-r5l76v"}
														data-styles-preset={"eqqdXNUnF"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"mobile application."}
													</motion.h2>
												</React.Fragment>
											),
										},
										YaGqp8wc_: {
											children: (
												<React.Fragment>
													<motion.h3
														className={"framer-styles-preset-hjktpe"}
														data-styles-preset={"RGFkKCDOm"}
														style={{
															"--framer-text-color":
																"var(--extracted-a0htzi, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
														}}
													>
														{"mobile application."}
													</motion.h3>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h1
										className={"framer-styles-preset-fqiunk"}
										data-styles-preset={"RWGve82MW"}
										style={{
											"--framer-text-color":
												"var(--extracted-gdpscs, var(--variable-reference-M3xrlQMNd-dowJGOcnx))",
										}}
									>
										{"mobile application."}
									</motion.h1>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-kYndM.framer-91pv9h, .framer-kYndM .framer-91pv9h { display: block; }",
	".framer-kYndM.framer-12elvc5 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 524px; }",
	".framer-kYndM .framer-yiut5d { flex: none; height: 80px; overflow: visible; position: relative; width: 524px; }",
	".framer-kYndM .framer-18emmmu { bottom: -320px; flex: none; height: auto; left: -2px; position: absolute; white-space: pre; width: auto; }",
	".framer-kYndM .framer-f1jmb3 { bottom: -240px; flex: none; height: auto; left: -2px; position: absolute; white-space: pre; width: auto; }",
	".framer-kYndM .framer-16027zo { bottom: 0px; flex: none; height: auto; left: 0px; position: absolute; white-space: pre; width: auto; }",
	".framer-kYndM .framer-1314qhq { flex: none; height: auto; left: -2px; position: absolute; top: 250%; white-space: pre; width: auto; }",
	".framer-kYndM .framer-1p9bmdu { bottom: -80px; flex: none; height: auto; left: 0px; position: absolute; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-kYndM.framer-12elvc5 { gap: 0px; } .framer-kYndM.framer-12elvc5 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-kYndM.framer-12elvc5 > :first-child { margin-top: 0px; } .framer-kYndM.framer-12elvc5 > :last-child { margin-bottom: 0px; } }",
	".framer-kYndM.framer-v-15qdun0 .framer-18emmmu { bottom: -240px; left: 1px; }",
	".framer-kYndM.framer-v-15qdun0 .framer-f1jmb3 { bottom: -160px; left: 1px; }",
	".framer-kYndM.framer-v-15qdun0 .framer-16027zo { bottom: unset; height: 80px; left: 1px; top: -80px; }",
	".framer-kYndM.framer-v-15qdun0 .framer-1314qhq { left: 1px; top: 150%; }",
	".framer-kYndM.framer-v-15qdun0 .framer-1p9bmdu { bottom: unset; top: 50%; }",
	".framer-kYndM.framer-v-dnoi0v .framer-18emmmu { bottom: -160px; left: 0px; }",
	".framer-kYndM.framer-v-dnoi0v .framer-f1jmb3, .framer-kYndM.framer-v-1vdosr9 .framer-18emmmu, .framer-kYndM.framer-v-1lwv4yd .framer-f1jmb3 { bottom: -80px; left: 0px; }",
	".framer-kYndM.framer-v-dnoi0v .framer-16027zo { bottom: unset; height: 80px; top: -160px; }",
	".framer-kYndM.framer-v-dnoi0v .framer-1314qhq, .framer-kYndM.framer-v-1lwv4yd .framer-1314qhq, .framer-kYndM.framer-v-z1h531 .framer-1314qhq { left: 0px; top: 50%; }",
	".framer-kYndM.framer-v-dnoi0v .framer-1p9bmdu, .framer-kYndM.framer-v-1lwv4yd .framer-1p9bmdu { bottom: 80px; }",
	".framer-kYndM.framer-v-1vdosr9 .framer-f1jmb3, .framer-kYndM.framer-v-18cyl7s .framer-18emmmu, .framer-kYndM.framer-v-86z536 .framer-f1jmb3, .framer-kYndM.framer-v-kjbmn5 .framer-18emmmu, .framer-kYndM.framer-v-yll8be .framer-f1jmb3, .framer-kYndM.framer-v-y9w877 .framer-18emmmu { bottom: unset; left: 0px; top: 50%; }",
	".framer-kYndM.framer-v-1vdosr9 .framer-16027zo { bottom: unset; height: 80px; top: -240px; }",
	".framer-kYndM.framer-v-1vdosr9 .framer-1314qhq, .framer-kYndM.framer-v-yll8be .framer-1314qhq { left: 0px; top: -50%; }",
	".framer-kYndM.framer-v-1vdosr9 .framer-1p9bmdu, .framer-kYndM.framer-v-86z536 .framer-1p9bmdu { bottom: 160px; }",
	".framer-kYndM.framer-v-18cyl7s .framer-f1jmb3, .framer-kYndM.framer-v-kjbmn5 .framer-f1jmb3 { bottom: unset; left: 0px; top: -80px; }",
	".framer-kYndM.framer-v-18cyl7s .framer-16027zo { bottom: unset; height: 80px; top: -320px; }",
	".framer-kYndM.framer-v-18cyl7s .framer-1314qhq, .framer-kYndM.framer-v-y9w877 .framer-1314qhq { left: 0px; top: -150%; }",
	".framer-kYndM.framer-v-18cyl7s .framer-1p9bmdu, .framer-kYndM.framer-v-kjbmn5 .framer-1p9bmdu { bottom: 240px; }",
	".framer-kYndM.framer-v-lz4yr2 .framer-yiut5d, .framer-kYndM.framer-v-1dczw7q .framer-yiut5d, .framer-kYndM.framer-v-1lwv4yd .framer-yiut5d, .framer-kYndM.framer-v-86z536 .framer-yiut5d, .framer-kYndM.framer-v-kjbmn5 .framer-yiut5d { height: 56px; }",
	".framer-kYndM.framer-v-lz4yr2 .framer-18emmmu { bottom: unset; left: 0px; top: 621%; }",
	".framer-kYndM.framer-v-lz4yr2 .framer-f1jmb3, .framer-kYndM.framer-v-1t062nr .framer-1314qhq { left: 0px; }",
	".framer-kYndM.framer-v-lz4yr2 .framer-16027zo, .framer-kYndM.framer-v-1t062nr .framer-16027zo { bottom: unset; top: 0px; }",
	".framer-kYndM.framer-v-lz4yr2 .framer-1314qhq { left: 0px; top: 336%; }",
	".framer-kYndM.framer-v-1dczw7q.framer-12elvc5 { cursor: pointer; }",
	".framer-kYndM.framer-v-1dczw7q .framer-18emmmu { bottom: unset; left: 0px; top: 477%; }",
	".framer-kYndM.framer-v-1dczw7q .framer-f1jmb3 { bottom: -159px; left: 0px; }",
	".framer-kYndM.framer-v-1dczw7q .framer-16027zo { bottom: unset; top: -81px; }",
	".framer-kYndM.framer-v-1dczw7q .framer-1314qhq { left: 0px; top: 191%; }",
	".framer-kYndM.framer-v-1dczw7q .framer-1p9bmdu { bottom: 1px; }",
	".framer-kYndM.framer-v-1lwv4yd .framer-18emmmu { bottom: unset; left: 0px; top: 336%; }",
	".framer-kYndM.framer-v-1lwv4yd .framer-16027zo { bottom: unset; top: -160px; }",
	".framer-kYndM.framer-v-86z536 .framer-18emmmu { bottom: unset; left: 0px; top: 193%; }",
	".framer-kYndM.framer-v-86z536 .framer-16027zo { bottom: unset; top: -240px; }",
	".framer-kYndM.framer-v-86z536 .framer-1314qhq { left: 0px; top: -93%; }",
	".framer-kYndM.framer-v-kjbmn5 .framer-16027zo { bottom: unset; top: -320px; }",
	".framer-kYndM.framer-v-kjbmn5 .framer-1314qhq { left: 0px; top: -236%; }",
	".framer-kYndM.framer-v-1t062nr .framer-yiut5d, .framer-kYndM.framer-v-x5j6he .framer-yiut5d, .framer-kYndM.framer-v-z1h531 .framer-yiut5d, .framer-kYndM.framer-v-yll8be .framer-yiut5d, .framer-kYndM.framer-v-y9w877 .framer-yiut5d { height: 44px; }",
	".framer-kYndM.framer-v-1t062nr .framer-18emmmu { bottom: unset; left: 0px; top: 452%; }",
	".framer-kYndM.framer-v-1t062nr .framer-f1jmb3 { bottom: -132px; left: 0px; }",
	".framer-kYndM.framer-v-1t062nr .framer-1p9bmdu { bottom: -44px; }",
	".framer-kYndM.framer-v-x5j6he .framer-18emmmu { bottom: unset; left: 0px; top: 350%; }",
	".framer-kYndM.framer-v-x5j6he .framer-f1jmb3 { bottom: -88px; left: 0px; }",
	".framer-kYndM.framer-v-x5j6he .framer-16027zo { bottom: unset; top: -44px; }",
	".framer-kYndM.framer-v-x5j6he .framer-1314qhq { left: 0px; top: 150%; }",
	".framer-kYndM.framer-v-x5j6he .framer-1p9bmdu { bottom: 0px; }",
	".framer-kYndM.framer-v-z1h531 .framer-18emmmu { bottom: unset; left: 0px; top: 250%; }",
	".framer-kYndM.framer-v-z1h531 .framer-f1jmb3 { bottom: -44px; left: 0px; }",
	".framer-kYndM.framer-v-z1h531 .framer-16027zo { bottom: unset; top: -88px; }",
	".framer-kYndM.framer-v-z1h531 .framer-1p9bmdu { bottom: 44px; }",
	".framer-kYndM.framer-v-yll8be .framer-18emmmu { bottom: unset; left: 0px; top: 150%; }",
	".framer-kYndM.framer-v-yll8be .framer-16027zo { bottom: unset; top: -132px; }",
	".framer-kYndM.framer-v-yll8be .framer-1p9bmdu { bottom: 88px; }",
	".framer-kYndM.framer-v-y9w877 .framer-f1jmb3 { bottom: unset; left: 0px; top: -44px; }",
	".framer-kYndM.framer-v-y9w877 .framer-16027zo { bottom: unset; top: -176px; }",
	".framer-kYndM.framer-v-y9w877 .framer-1p9bmdu { bottom: 132px; }",
	...css3,
	...css,
	...css2,
];
var FramerdowJGOcnx = withCSS(Component, css4, "framer-kYndM");
var stdin_default = FramerdowJGOcnx;
FramerdowJGOcnx.displayName = "Text Animation [Hero Section]";
FramerdowJGOcnx.defaultProps = {
	height: 80,
	width: 524,
};
addPropertyControls(FramerdowJGOcnx, {
	variant: {
		options: [
			"Y3Wng9ic3",
			"NvQlB76ip",
			"WJCNW1X6P",
			"BydgrkuMq",
			"WehEgKult",
			"uIE50kYTK",
			"KsbdY7ojc",
			"rclV5YU1T",
			"En65AYq8W",
			"i5eDoNflh",
			"OGKVC19Xt",
			"fvHknp2PU",
			"Hn0EEn9cO",
			"oQvYtI6U2",
			"YaGqp8wc_",
		],
		optionTitles: [
			"Desktop 1",
			"Desktop 2",
			"Desktop 3",
			"Desktop 4",
			"Desktop 5",
			"Tablet",
			"Tablet 2",
			"Tablet 3",
			"Tablet 4",
			"Tablet 5",
			"Mobile 1",
			"Mobile 2",
			"Mobile 3",
			"Mobile 4",
			"Mobile 5",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	AKBUKrFCf: {
		defaultValue: "digital product.",
		displayTextArea: false,
		title: "Title 1",
		type: ControlType.String,
	},
	pORcANL6Z: {
		defaultValue: "landing pages.",
		displayTextArea: false,
		title: "Title2",
		type: ControlType.String,
	},
	UlOOaXh04: {
		defaultValue: "visual identity.",
		displayTextArea: false,
		title: "Title 3",
		type: ControlType.String,
	},
	KzPuVZC7w: {
		defaultValue: "mobile application.",
		displayTextArea: false,
		title: "Title 4",
		type: ControlType.String,
	},
	M3xrlQMNd: {
		defaultValue:
			'var(--token-537bfcfa-1832-4a09-9413-729564804849, rgb(52, 65, 74)) /* {"name":"Primary / Blue [500]"} */',
		title: "Color 2",
		type: ControlType.Color,
	},
});
addFonts(
	FramerdowJGOcnx,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:text-animation-hero-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "OGKVC19Xt",
	lg: "WehEgKult",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TextAnimationHeroSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"5393b9314a5482450bd063fdec2abaa51e33580d8faa88cac3362a540b16df77"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var text_animation_hero_section_default = ComponentWithRoot;
export { text_animation_hero_section_default as default };
